# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20180817_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='majors',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='school.Major', verbose_name='\u4e13\u4e1a'),
        ),
    ]
