# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_party_type'),
        ('course', '0005_auto_20190308_2010'),
        ('school', '0020_clazzcourse_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clazzcourse',
            name='party',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_clazzcourses', to='saas.Party', verbose_name='\u56e2\u4f53'),
        ),
        migrations.AlterUniqueTogether(
            name='clazzcourse',
            unique_together=set([('party', 'clazz', 'course')]),
        ),
    ]
