# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models


def init_is_bind(apps, schema_editor):
    Student = apps.get_model('school', 'Student')
    for s in Student.objects.all():
        p = s.user.password
        s.is_bind = p is not None and  not p.startswith('!')
        s.save()


class Migration(migrations.Migration):
    dependencies = [
        ('school', '0022_auto_20190322_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_bind',
            field=models.BooleanField(default=False, verbose_name='\u5df2\u7ed1'),
        ),
        migrations.RunPython(init_is_bind)
    ]
