# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-05-13 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200219_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('party', 'name'), 'permissions': (('view_all_course', '\u67e5\u770b\u6240\u6709\u8bfe\u7a0b'), ('view_course_sensitivity', '\u67e5\u770b\u8bfe\u7a0b\u654f\u611f\u4fe1\u606f')), 'verbose_name': '\u8bfe\u7a0b', 'verbose_name_plural': '\u8bfe\u7a0b'},
        ),
    ]
