[tool.poetry]
name = "pjisp-template-name"
version = "0.1.0"
description = "PJISP get template name from repository name"
authors = ["Jelena Dokic <jrubics@hacke.rs>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^2.7"
click = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
pjisp_template_name = 'pjisp_template_name:get_name'
