[tool.poetry]
name = "sentile"
version = "0.1.0"
description = "Sentinel tile utilities"
authors = ["Robofarm <hello@robofarm.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
sentile = "sentile.scripts.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
