# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-02-10 00:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0007_auto_20191101_1652'),
        ('dailylog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_date', models.DateField(db_index=True, verbose_name='\u65e5\u671f')),
                ('owner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7')),
                ('metics', models.CharField(max_length=128, verbose_name='\u6307\u6807')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='\u6570\u503c')),
                ('user_count', models.PositiveIntegerField(default=0, verbose_name='\u7528\u6237\u6570')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('owner_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dailylog_stats', to='saas.Party', verbose_name='\u56e2\u4f53')),
            ],
            options={
                'verbose_name': '\u7edf\u8ba1',
                'verbose_name_plural': '\u7edf\u8ba1',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together=set([('the_date', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together=set([('the_date', 'owner_type', 'owner_id', 'metics')]),
        ),
    ]
