# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-05-01 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailylog', '0005_performance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ('-update_time',), 'verbose_name': '\u8868\u73b0', 'verbose_name_plural': '\u8868\u73b0'},
        ),
        migrations.AlterField(
            model_name='performance',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
