[tool.poetry]
name = "etlaas-stream"
version = "20.7.6"
description = "Convenience classes for working with data streams."
authors = ["Andrew Meier <ameier38@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastjsonschema = "^2.14.4"
simplejson = "^3.17.0"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
