language: python
python:
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
before_script: cd tests
# command to run tests
script: nosetests --with-coverage --cover-package=litmos
after_success:
  - coveralls
