# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-04-08 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='reply',
            field=models.CharField(blank=True, default=b'', max_length=256, verbose_name=b'\xe7\xad\x94\xe5\xa4\x8d'),
        ),
    ]
