# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-04-10 01:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_operator(apps, schema_editor):
    Verify = apps.get_model('verify', 'Verify')
    User = apps.get_model('auth', 'User')
    for v in Verify.objects.all():
        v.operator = v.user
        v.user = User.objects.get(id=v.content.get('user'))
        v.save()
        print v


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verify', '0002_verify_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifies_operated', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\xae\xa1\xe6\xa0\xb8\xe5\x91\x98'),
        ),
        migrations.AlterField(
            model_name='verify',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifies', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7'),
        ),
        migrations.RunPython(add_operator)
    ]
