[tool.poetry]
name = "sysfs"
version = "0.1.0"
description = ""
authors = ["Gregory C. Oakes <gregoryoakes@fastmail.com>"]

[tool.poetry.dependencies]
python = "^2.7 || ^3.7 || ^3.8"

[tool.poetry.dev-dependencies]
pytest = [
    { version = "4.6", python = "<3.5" },
    { version = "^5.2", python = ">=3.5"},
]
flakehell = {version = "^0.4.5", python = ">=3.5"}
black = {version = "^19.10b0", python = ">=3.6"}
isort = "^4.3.21"
tox = "^3.15.1"
flake8 = "^3.8.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.flakehell]
max_line_length = 89

[tool.flakehell.plugins]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
