
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-31T12:55:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "af11f5be21ecc5630dbfeca7f17f49617f362715",
 "version": "1.2.5-alpha.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
