# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20191101_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anchor',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u951a\u70b9'),
        ),
        migrations.AddField(
            model_name='comment',
            name='context',
            field=models.TextField(blank=True, default='', verbose_name='\u4e0a\u4e0b\u6587'),
        ),
    ]
