# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-17 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
