# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-07-08 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0010_auto_20200617_1558'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0009_favorite_notes_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([('party', 'user', 'content_type', 'object_id')]),
        ),
    ]
