[tool.poetry]
name = "col"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pytest = "^5.4.3"

[tool.poetry.dev-dependencies]
numpy = "^1.19.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
