# Generated by Django 3.0.8 on 2020-07-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_standardize_description'),
        ('lifecycles', '0007_auto_20200722_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.Tenant'),
        ),
    ]
