[tool.poetry]
name = "pjisp_diff"
version = "0.1.9"
description = "PJISP diff check"
authors = ["Jelena Dokic <jrubics@hacke.rs>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^2.7"
click = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
pjisp_diff = 'pjisp_diff:diff'
