[tool.poetry]
name = "wagtail-meilisearch"
version = "0.11.0"
description = "A MeiliSearch backend for Wagatil"
authors = ["Hactar <systems@hactar.is>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/hactar-is/wagtail-meilisearch"
repository = "https://github.com/hactar-is/wagtail-meilisearch"
keywords = ["wagtail", "django", "search", "meilisearch"]
classifiers=[
    'Environment :: Web Environment',
    'Framework :: Django',
    'Framework :: Wagtail',
    'Framework :: Wagtail :: 2',
    'Intended Audience :: Developers',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"

arrow = "^0.15.0"
meilisearch = "^0.11.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
