
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-07T16:06:11+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d23eda89df012f7560dd67224b5cdc33dcce63a2",
 "version": "2.8.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
