# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-12 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signins', to='saas.Party', verbose_name='\u56e2\u4f53'),
        ),
    ]
