# AUTOMATICALLY GENERATED AS DERIVATIVE OF skbuild.command PACKAGE (cythontools)
from skbuild.command.generate_source_manifest import os as _skbuild_command_generate_source_manifest_os
from skbuild.command.generate_source_manifest import subprocess as _skbuild_command_generate_source_manifest_subprocess
from skbuild.command.generate_source_manifest import sys as _skbuild_command_generate_source_manifest_sys
from skbuild.command.generate_source_manifest import Command as _skbuild_command_generate_source_manifest_Command
from skbuild.command.generate_source_manifest import set_build_base_mixin as _skbuild_command_generate_source_manifest_set_build_base_mixin
from skbuild.command.generate_source_manifest import SKBUILD_DIR as _skbuild_command_generate_source_manifest_SKBUILD_DIR
from skbuild.command.generate_source_manifest import SKBUILD_MARKER_FILE as _skbuild_command_generate_source_manifest_SKBUILD_MARKER_FILE
from skbuild.command.generate_source_manifest import new_style as _skbuild_command_generate_source_manifest_new_style
from skbuild.command.generate_source_manifest import generate_source_manifest as _skbuild_command_generate_source_manifest_generate_source_manifest


class Command(_skbuild_command_generate_source_manifest_Command):
    pass

class set_build_base_mixin(_skbuild_command_generate_source_manifest_set_build_base_mixin):
    pass

class generate_source_manifest(_skbuild_command_generate_source_manifest_generate_source_manifest):
    pass


os = _skbuild_command_generate_source_manifest_os
subprocess = _skbuild_command_generate_source_manifest_subprocess
sys = _skbuild_command_generate_source_manifest_sys
SKBUILD_DIR = _skbuild_command_generate_source_manifest_SKBUILD_DIR
SKBUILD_MARKER_FILE = _skbuild_command_generate_source_manifest_SKBUILD_MARKER_FILE
new_style = _skbuild_command_generate_source_manifest_new_style
