# AUTOMATICALLY GENERATED AS DERIVATIVE OF skbuild.command PACKAGE (cythontools)
from skbuild.command.install_lib import distutils_log as _skbuild_command_install_lib_distutils_log
from skbuild.command.install_lib import set_build_base_mixin as _skbuild_command_install_lib_set_build_base_mixin
from skbuild.command.install_lib import distribution_hide_listing as _skbuild_command_install_lib_distribution_hide_listing
from skbuild.command.install_lib import new_style as _skbuild_command_install_lib_new_style
from skbuild.command.install_lib import install_lib as _skbuild_command_install_lib_install_lib


class set_build_base_mixin(_skbuild_command_install_lib_set_build_base_mixin):
    pass

class install_lib(_skbuild_command_install_lib_install_lib):
    pass


distutils_log = _skbuild_command_install_lib_distutils_log
distribution_hide_listing = _skbuild_command_install_lib_distribution_hide_listing
new_style = _skbuild_command_install_lib_new_style
