[tool.poetry]
name = "mongoset"
version = "0.2.2"
description = "Pythonic wrapper around pymongo that can act as a drop-in replacement for dataset"
authors = ["InnovativeInventor <root@max.fan>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/TadpoleTutoring/mongoset"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]


[tool.poetry.dependencies]
python = "^3.8"
pymongo = "^3.10.1"
dnspython = "^1.16.0"
pytest-race = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
