[tool.poetry]
name = "typer-passwd"
version = "0.1.3"
description = "Simple CLI app that generates random passwords."
authors = ["Mrnobody <mrcartoonster@icloud.com>"]
readme = "README.md"

[tool.poetry.scripts]
typer-passwd = "typer_passwd.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.3.0"}
colorful = "^0.5.4"
yakutils = "^1.7.0"
pyperclip = "^1.8.0"
wasabi = "^0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-emoji = "^0.2.0"
pytest-picked = "^0.4.4"
pytest-instafail = "^0.4.2"
pygments = "^2.6.1"
ipython = "^7.16.1"
pre-commit = "^2.6.0"
interrogate = "^1.2.0"
pytest-mypy = "^0.6.2"
pytest-cov = "^2.10.0"
pytest-html = "^2.1.1"
Commitizen = "^1.23.0"
conventional-JIRA = "^0.2.2"
commitizen-emoji = "^0.1.5"
cz_conventional_JIRA = "^0.2.0"
black = {version = "^19.10b0", allow-prereleases = true}
pretty_errors = "^1.2.17"
termtosvg = "^1.1.0"

[tool.commitizen]
name = "cz_jira"
version = "0.1.0"
version_files = [
    "src/__version__.py",
    "pyproject.toml:version"
]
style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"]
]

[tool.pytest.ini_options]
addopts = "-rsxX -l --tb=short --strict --emoji -vvv"
markers = [
    "first",
    "second"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
