language: python
cache: pip
dist: xenial

matrix:
  include:
    - python: 3.6
      before_install:
        - sudo add-apt-repository ppa:mc3man/xerus-media -y
        - sudo apt-get update -qq
        - sudo apt-get install -qq ubuntu-restricted-extras ffmpeg
      before_script:
        ffmpeg --help
    - python: 3.7
      before_install:
        - sudo add-apt-repository ppa:mc3man/xerus-media -y
        - sudo apt-get update -qq
        - sudo apt-get install -qq ubuntu-restricted-extras ffmpeg
      before_script:
        ffmpeg --help
    - python: 3.8
      before_install:
        - sudo add-apt-repository ppa:mc3man/xerus-media -y
        - sudo apt-get update -qq
        - sudo apt-get install -qq ubuntu-restricted-extras ffmpeg
      before_script:
        ffmpeg --help
    - python: 3.8
      env: TOXENV=doc
    - python: 3.8
      env: TOXENV=check
  allow_failures:
    - env: TOXENV=check

install: pip install -U tox-travis

script: tox -- -v

after_success:
  - pip install codecov
  - codecov

notifications:
    irc: "chat.freenode.net#sigal"
