
DEFAULT_TICK_INTERVAL_MS = 100
DEFAULT_UPDATE_WORKER_INTERVAL_MS = 500
DEFAULT_UPDATE_TASK_INTERVAL_MS = 15000

DEFAULT_VALIDATE_REPORT_INTERVAL_MS = 2000
DEFAULT_CHECK_REVISION_INTERVAL_MS = 2000



BT_KEYWORD = 'BehaviorTree'


#finder algorithm
ASTAR_FINDER = 'ASTAR_FINDER'
BEST_FIRST_FINDER = 'BEST_FIRST_FINDER'
DIJKSTRA_FINDER = 'DIJKSTRA_FINDER'
DEFAULT_FINDER_ALGORITHM = ASTAR_FINDER
