
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-01T14:58:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "042e90e25d18d8c67673624b5a812eb82147e4fc",
 "version": "2020.08.01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
