# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-10 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='organizing_institution_bar_code',
            new_name='oibc',
        ),
        migrations.AlterField(
            model_name='trainee',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u672a\u5b9e\u4e60'), (1, '\u5b9e\u4e60'), (2, '\u6b63\u5f0f\u5458\u5de5'), (4, '\u79bb\u804c'), (5, '\u4e2d\u8f6c\u9ad8'), (6, '\u5347\u5b66'), (7, '\u53c2\u519b')], db_index=True, default=0, verbose_name='\u5b9e\u4e60\u72b6\u6001'),
        ),
    ]
