
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b1a664e21948bf6644c7c23cbf90532c78befdd3",
 "version": "1.16.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
