
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4ac6b1699c0137d799454e608ba0314b5a918f5f",
 "version": "7.6.2.beta2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
