[tool.poetry]
name = "django_require_login"
version = "1.1.0"
description = "Middleware to require login for all Django URLs"
authors = ["Steven Pate <steven@laac.dev>", "Mike Grouchy <mgrouchy@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/laactech/django-require-login"
keywords = [
    "django",
    "login required",
    "authentication",
    "login",
    "python",
]
classifiers = [
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Environment :: Web Environment",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
]

[tool.poetry.dependencies]
python = "^3.6"
django = ">= 2.2, < 4.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.0.0"
mock = "^4.0.0"
tox = "^3.14.0"
pytest-django = "^3.6.0"
pytest-cov = "^2.8.1"
pytest = "^6.0.0"

[tool.tox]
legacy_tox_ini = """
[tox]
skipsdist = True
envlist =
       {py36,py37,py38}-django{22,30,31}
       lint

[tox:.package]
# note tox will use the same python version as under what tox is installed to package
# so unless this is python 3 you can require a given python version for the packaging
# environment via the basepython key
basepython = python3

[travis:env]
DJANGO =
    2.2: django22
    3.0: django30
    3.1: django31

[testenv]
recreate = true
whitelist_externals = poetry
install_command = poetry add -D {packages}
commands =
    poetry install -vvv
    poetry add asgiref
    poetry run pytest --cov=django_require_login
envdir = {toxworkdir}/venvs/{envname}
deps =
        django22: django>=2.2,<3.0
        django30: django>=3.0,<3.1
        django31: django>=3.1,<3.2

[testenv:lint]
commands = pre-commit run -a
"""

[tool.pytest.ini_options]
python_files = "test*.py *tests.py tests*.py *test.py"
DJANGO_SETTINGS_MODULE = "sample_project.settings"

[tool.isort]
known_third_party = ["django", "mock"]
profile = "black"
line_length = 90

[tool.black]
line-length = 90
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
