# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('school', '0002_auto_20170930_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='clazz',
            name='party',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='school_clazzs', to='saas.Party', verbose_name='\u56e2\u4f53'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='party',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='school_grades', to='saas.Party', verbose_name='\u56e2\u4f53'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='party',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='school_sessions', to='saas.Party', verbose_name='\u56e2\u4f53'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='party',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='school_students', to='saas.Party', verbose_name='\u56e2\u4f53'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='party',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='school_teachers', to='saas.Party', verbose_name='\u56e2\u4f53'),
            preserve_default=False,
        ),
    ]
