# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-14 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20171010_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clazz',
            name='entrance_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_clazzs', to='school.Session', verbose_name='\u5165\u5b66\u5c4a\u522b'),
        ),
        migrations.AlterUniqueTogether(
            name='clazz',
            unique_together=set([('school', 'entrance_session', 'grade', 'number')]),
        ),
    ]
