# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-22 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180812_2146'),
        ('school', '0012_student_majors'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='clazz',
        #     name='courses',
        #     field=models.ManyToManyField(blank=True, related_name='school_classes', to='course.Course', verbose_name='\u8bfe\u7a0b'),
        # ),
        migrations.AlterField(
            model_name='student',
            name='majors',
            field=models.ManyToManyField(blank=True, related_name='students', to='school.Major', verbose_name='\u4e13\u4e1a'),
        ),
    ]
