# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20180822_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clazz',
            unique_together=set([('school', 'name')]),
        ),
        migrations.AlterModelOptions(
            name='clazz',
            options={'ordering': ('school', 'grade', 'name'), 'verbose_name': '\u73ed\u7ea7', 'verbose_name_plural': '\u73ed\u7ea7'},
        ),
        migrations.AddField(
            model_name='clazz',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='\u4ee3\u7801'),
        ),
        migrations.AddField(
            model_name='clazz',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='\u7b80\u79f0'),
        ),
        migrations.AlterField(
            model_name='clazz',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='\u540d\u79f0'),
        ),
        migrations.RemoveField(
            model_name='clazz',
            name='number',
        ),
    ]
