# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-15 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clazz',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='\u4ee3\u7801'),
        ),
    ]
