# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-12 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def init_party_of_clazzcourse(apps, schema_editor):
    ClazzCourse = apps.get_model('school', 'ClazzCourse')
    for a in ClazzCourse.objects.all():
        print a
        try:
            a.party = a.clazz.party
            a.save()
        except Exception, e:
            print e


class Migration(migrations.Migration):
    dependencies = [
        ('saas', '0005_party_type'),
        ('school', '0019_auto_20190312_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='clazzcourse',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='school_clazzcourses', to='saas.Party', verbose_name='\u56e2\u4f53'),
        ),
        migrations.RunPython(init_party_of_clazzcourse)
    ]
