# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-23 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_student_is_bind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clazz',
            options={'ordering': ('school', 'grade', 'name'), 'permissions': (('view_all_clazz', '\u67e5\u770b\u6240\u6709\u73ed\u7ea7'), ('view_clazz_sensitivity', '\u67e5\u770b\u73ed\u7ea7\u654f\u611f\u4fe1\u606f')), 'verbose_name': '\u73ed\u7ea7', 'verbose_name_plural': '\u73ed\u7ea7'},
        ),
        migrations.AlterModelOptions(
            name='clazzcourse',
            options={'permissions': (('view_all_clazzcourse', '\u67e5\u770b\u6240\u6709\u73ed\u7ea7\u8bfe\u7a0b'),), 'verbose_name': '\u73ed\u7ea7\u8bfe\u7a0b', 'verbose_name_plural': '\u73ed\u7ea7\u8bfe\u7a0b'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view_all_student', '\u67e5\u770b\u6240\u6709\u5b66\u751f'), ('view_student_sensitivity', '\u67e5\u770b\u5b66\u751f\u654f\u611f\u4fe1\u606f')), 'verbose_name': '\u5b66\u751f', 'verbose_name_plural': '\u5b66\u751f'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('party', '-create_time'), 'permissions': (('view_all_teacher', '\u67e5\u770b\u6240\u6709\u8001\u5e08'),), 'verbose_name': '\u8001\u5e08', 'verbose_name_plural': '\u8001\u5e08'},
        ),
    ]
