# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-19 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20191006_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('number',), 'permissions': (('view_all_student', '\u67e5\u770b\u6240\u6709\u5b66\u751f'), ('view_student_sensitivity', '\u67e5\u770b\u5b66\u751f\u654f\u611f\u4fe1\u606f')), 'verbose_name': '\u5b66\u751f', 'verbose_name_plural': '\u5b66\u751f'},
        ),
    ]
