# Generated by Django 2.2.12 on 2020-07-23 12:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("django_dbq_exports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="export_params",
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
