
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-27T13:38:58-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ef1ee7833ef81f95a3984d355c0e28577d09171",
 "version": "0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
