# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-07 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20171205_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='seconds',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='\u5355\u4f4d(\u79d2)', null=True, verbose_name='\u7528\u65f6'),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('party', 'user', 'paper')]),
        ),
    ]
