# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-07 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_szuprefix.utils.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('exam', '0003_auto_20171207_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', django_szuprefix.utils.modelutils.JSONField(verbose_name='\u8be6\u60c5')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stat', to='exam.Paper', verbose_name='\u8bd5\u5377')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_stats', to='saas.Party', verbose_name='\u56e2\u4f53')),
            ],
            options={
                'verbose_name': '\u7edf\u8ba1',
                'verbose_name_plural': '\u7edf\u8ba1',
            },
        ),
    ]
