# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-25 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20180713_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
