# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_performance_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_break_through',
            field=models.BooleanField(default=True, verbose_name='\u95ef\u5173'),
        ),
    ]
