# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20190811_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='\u6709\u6548'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='owner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b'),
        ),
    ]
