# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('brief_name', models.CharField(blank=True, max_length=128, verbose_name='\u7b80\u79f0')),
                ('oibc', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7ec4\u7ec7\u673a\u6784\u4ee3\u7801')),
                ('usci', models.CharField(blank=True, max_length=18, null=True, verbose_name='\u7edf\u4e00\u793e\u4f1a\u4fe1\u7528\u4ee3\u7801')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='logo')),
                ('establish_date', models.DateField(blank=True, null=True, verbose_name='\u521b\u7acb\u65e5\u671f')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5730\u5740')),
                ('website', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u7f51\u7ad9')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_organization', to='saas.Party', verbose_name='\u56e2\u4f53')),
            ],
            options={
                'verbose_name': '\u7ec4\u7ec7\u673a\u6784',
                'verbose_name_plural': '\u7ec4\u7ec7\u673a\u6784',
            },
        ),
    ]
