#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='pubpack',
      version='0.1',
      description='An amazing sample package!',
      author='Frank Nostrame',
      author_email='nostrame@gmail.com',
      url='http://nostrame.com',
      py_modules=['pubpack'],
     )
