dist: bionic
language: cpp
os:
  - linux
compiler:
  - clang

addons:
   apt:
      packages: ['clang-8' , 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl']

env:
  # Build VIDARDB
  - JOB_NAME=build

install:
  # Build gflags (Remove when gflags available through Travis)
  - pushd /tmp/ && curl -L https://github.com/gflags/gflags/archive/v2.1.2.tar.gz -o gflags.tar.gz && tar xfz gflags.tar.gz && cd gflags-2.1.2 && cmake . && make && popd

before_script:
  # Add gflags to include/library paths (Remove when gflags available through Travis)
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/tmp/gflags-2.1.2/lib"
  - export LIBRARY_PATH="$LIBRARY_PATH:/tmp/gflags-2.1.2/lib"
  - export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/tmp/gflags-2.1.2/include"
  - export CPU_CORES=`cat /proc/cpuinfo | grep processor | wc -l`
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' ]]; then CXX=clang++-8; fi
  # Limit the maximum number of open file descriptors to 2000
  - ulimit -n 2000 || true

script:
  # Compile all vidardb codes
  - OPT="-DTRAVIS -DVIDARDB" V=1 make -j${CPU_CORES} release
  - OPT="-DTRAVIS -DVIDARDB" V=1 DEBUG_LEVEL=0 make -j${CPU_CORES} all
  # - OPT="-DTRAVIS -DVIDARDB" V=1 make -j${CPU_CORES} dbg
  # Run all e2e tests
  - cd test/e2e && make e2e-test
  # Compile all example codes
  - cd ../../examples && OPT="-DTRAVIS -DVIDARDB" V=1 make all
