# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-02-22 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_auto_20191101_1652'),
        ('media', '0004_auto_20200221_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_lecturers', to='saas.Party', verbose_name='\u56e2\u4f53')),
            ],
            options={
                'verbose_name': '\u8bb2\u5e08',
                'verbose_name_plural': '\u8bb2\u5e08',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='lecturer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='media.Lecturer', verbose_name='\u8bb2\u5e08'),
        ),
    ]
