
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-03T23:36:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f9df25f457a1b28417ded6f338a48e8468dcb9e",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
