[tool.poetry]
name = "linefolio"
version = "1.1.0"
description = "Backtest performance analysis and charting for MoonLine, but with pyfolio."
authors = ["Tim Wedde <timwedde@icloud.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
ipython = "^7.16.1"
matplotlib = "^3.3.0"
numpy = "^1.19.0"
pandas = "^1.0.5"
pytz = "^2020.1"
scipy = "^1.5.1"
scikit-learn = "^0.23.1"
seaborn = "^0.10.1"
empyrical = "^0.5.3"
quantrocket-moonshot = "^2.1.0"
quantrocket-moonchart = "^2.0.1"

[tool.poetry.dev-dependencies]
pdoc3 = "^0.8.1"
flake8 = "^3.7.9"
pytest = "^5.4.2"
codecov = "^2.0.22"
nose = "^1.3.7"
nose-parameterized = "^0.6.0"
runipy = "^0.1.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
