dist: bionic
sudo: false
language: python
python: 3.7
cache: pip
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover tests --verbose
