[tool.poetry]
name = "ntfsdump"
version = "1.1.0"
description = "A tool for exporting any files from an NTFS volume on a Raw Image file."
authors = ["sumeshi <j15322sn@gmail.com>"]
license = "MIT"
readme = "README.md"

repository = "https://github.com/sumeshi/ntfsdump"
homepage = "https://github.com/sumeshi/ntfsdump"

keywords = ['Windows']

[tool.poetry.scripts]
ntfsdump = 'ntfsdump:ntfsdump'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
mypy = "^0.782"
flake8 = "^3.8.3"
poetry = "^1.0.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
