[tool.poetry]
name = "coinmetrics-api-client"
version = "2020.07.26-alpha"
description = "Python client for Coin Metrics API v4."
authors = ["Coin Metrics <info@coinmetrics.io>", "Oleksandr Buchkovskyi <oleksandr@coinmetrics.io>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/coinmetrics-io/api-client-python"
packages = [{include = "coinmetrics"}]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
flake8 = "^3.8.3"
black = "^19.10b0"

[tool.poetry.scripts]
realpython = "reader.__main__:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

