# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-05 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_szuprefix.utils.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', django_szuprefix.utils.modelutils.JSONField(verbose_name='\u8be6\u60c5')),
                ('performance', django_szuprefix.utils.modelutils.JSONField(blank=True, null=True, verbose_name='\u6210\u7ee9\u8868\u73b0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ('-create_time',),
                'verbose_name': '\u7528\u6237\u7b54\u5377',
                'verbose_name_plural': '\u7528\u6237\u7b54\u5377',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='\u5f97\u5206')),
                ('detail', django_szuprefix.utils.modelutils.JSONField(blank=True, null=True, verbose_name='\u8be6\u60c5')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6210\u7ee9',
                'verbose_name_plural': '\u7528\u6237\u6210\u7ee9',
            },
        ),
        migrations.AlterField(
            model_name='paper',
            name='is_active',
            field=models.BooleanField(verbose_name='\u6709\u6548'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u6807\u9898'),
        ),
        migrations.AddField(
            model_name='performance',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performances', to='exam.Paper', verbose_name='\u8bd5\u5377'),
        ),
        migrations.AddField(
            model_name='performance',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_performances', to='saas.Party', verbose_name='\u56e2\u4f53'),
        ),
        migrations.AddField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_performances', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='answer',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='exam.Paper', verbose_name='\u8bd5\u5377'),
        ),
        migrations.AddField(
            model_name='answer',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_answers', to='saas.Party', verbose_name='\u56e2\u4f53'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_answers', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
