# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-29 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_answer_std_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ('-is_active', 'title', '-create_time'), 'permissions': (('view_all_paper', '\u67e5\u770b\u6240\u6709\u8bd5\u5377'),), 'verbose_name': '\u8bd5\u5377', 'verbose_name_plural': '\u8bd5\u5377'},
        ),
    ]
