# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='begin_time',
            field=models.DateTimeField(db_index=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='minutes',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='\u9650\u65f6(\u5206\u949f)'),
        ),
    ]
