# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-15 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20200311_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ('-is_active', 'order_number', '-create_time'), 'permissions': (('view_all_paper', '\u67e5\u770b\u6240\u6709\u8bd5\u5377'),), 'verbose_name': '\u8bd5\u5377', 'verbose_name_plural': '\u8bd5\u5377'},
        ),
        migrations.AddField(
            model_name='paper',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='\u6309\u6570\u5b57\u4ece\u5c0f\u5230\u5927\u6392\u5e8f', verbose_name='\u5e8f\u53f7'),
        ),
    ]
