# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from spaceone.api.sample.v1 import helloworld_pb2 as spaceone_dot_api_dot_sample_dot_v1_dot_helloworld__pb2


class GreeterStub(object):
    """desc: The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/spaceone.api.sample.v1.Greeter/SayHello',
                request_serializer=spaceone_dot_api_dot_sample_dot_v1_dot_helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_sample_dot_v1_dot_helloworld__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """desc: The greeting service definition.
    """

    def SayHello(self, request, context):
        """desc: Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=spaceone_dot_api_dot_sample_dot_v1_dot_helloworld__pb2.HelloRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_sample_dot_v1_dot_helloworld__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spaceone.api.sample.v1.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """desc: The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.sample.v1.Greeter/SayHello',
            spaceone_dot_api_dot_sample_dot_v1_dot_helloworld__pb2.HelloRequest.SerializeToString,
            spaceone_dot_api_dot_sample_dot_v1_dot_helloworld__pb2.HelloReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
