language: python
dist: xenial
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
before_install:
  - pip install --upgrade setuptools pip
install:
  - pip install --upgrade .[cache] pytest-cov
script:
  # disable automatic inclusion for coverage
  - pytest -p no:check-links --cov pytest_check_links --cov-report term-missing
after_success:
  - pip install codecov
  - codecov
