site_name: scGen Documentation
site_description: 'Documentation for ScGen, the generative model to predict single-cell perturbation response across cell types, studies and species.'
docs_dir: docs/sources
repo_url: http://github.com/theislab/scgen

pages:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Models:
    - VAE: 'models/vae.md'
    - utils: 'models/utils.md'
    - read_load: 'read_load.md'
    - plotting: 'plotting.md'

theme: readthedocs
