# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20180714_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view_student', '\u67e5\u770b\u5b66\u751f\u8d44\u6599'),), 'verbose_name': '\u5b66\u751f', 'verbose_name_plural': '\u5b66\u751f'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('view_teacher', '\u67e5\u770b\u8001\u5e08\u8d44\u6599'),), 'verbose_name': '\u8001\u5e08', 'verbose_name_plural': '\u8001\u5e08'},
        ),
    ]
