
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-27T09:53:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8cbe3cc7ceffe366e58e46d5b84a54e425cfd28",
 "version": "1.9.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
