
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-04T12:42:08+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b60d2805f8e74183f4079a1aac35640eda55c8eb",
 "version": "2.0.0rc6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
