
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-30T09:55:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6856eae72175c59b637a846f2214954d4610ceda",
 "version": "0.3.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
