# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-21 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20200617_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='notes_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='\u7b14\u8bb0\u6570'),
        ),
    ]
