# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-12 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_auto_20180713_0601'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('party', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set([('party', 'course', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('party', 'code')]),
        ),
    ]
