# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-17 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190322_1214'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='chapter',
            order_with_respect_to='course',
        ),
    ]
