[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"


[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"


[tool.poetry]
name = "paraplot"
version = "0.1.0"
description = "Parameter retrieval and plotting"
license = "MIT"

authors = ['Nikolai von Krusenstiern']

readme = "README.md"

repository = "https://github.com/cruisen/paraplot"

keywords = []

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.7"
json_minify = "^0.3.0"
pandas = "^1.1.0"
matplotlib = "^3.3.0"
IPython = "^7.17.0"
requests = "^2.24.0"
requests_cache = "^0.5.2"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]
mypy = "^0.782"

wemake-python-styleguide = "^0.14"
flake8-pytest-style = "^1.2"
nitpick = "^0.22"

safety = "^1.9"

pytest = "^5.4"
pytest-cov = "^2.10"
pytest-randomly = "^3.4"

sphinx = "^2.2"
sphinx-autodoc-typehints = "^1.10"
doc8 = "^0.8"
m2r = "^0.2"
tomlkit = "^0.6"
pre-commit = "^2.6.0"
