# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-26 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django_szuprefix.utils.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='context',
            field=django_szuprefix.utils.modelutils.JSONField(blank=True, default={}, verbose_name='\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u540d\u79f0'),
        ),
    ]
