# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-02-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20191226_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='\u5c01\u9762'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='\u5355\u4f4d: \u79d2.', verbose_name='\u65f6\u957f'),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='\u5355\u4f4d: \u6bd4\u7279Byte', verbose_name='\u5927\u5c0f'),
        ),
    ]
