# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-02-21 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20200207_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('owner_type', 'owner_id', 'name'), 'verbose_name': '\u89c6\u9891', 'verbose_name_plural': '\u89c6\u9891'},
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '\u8f6c\u7801\u4e2d'), (2, '\u5b8c\u6210'), (0, '\u5931\u8d25')], default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, help_text='\u5355\u4f4d: \u79d2.', verbose_name='\u65f6\u957f'),
        ),
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, help_text='\u5355\u4f4d: \u6bd4\u7279Byte', verbose_name='\u5927\u5c0f'),
        ),
    ]
