[tool.poetry]
name = "mesmer"
version = "0.0.1"
description = "mesmer sees through foregrounds"
authors = ["Ben Thorne <bn.thorne@googlemail.com>"]
readme = "README.md"
repository = "https://github.com/bthorne93/mesmer"

[tool.poetry.dependencies]
python = "^3.6"
astropy = "^4.0.1"
numpy = "^1.17 || ^1.18"
matplotlib = "^3.0.0"
pytest-astropy = {version = "^0.8.0", optional = true}
pyyaml = "^5.3.1"
h5py = "^2.10.0"
pytest = {version = "^5", optional = true}
sphinx = {version = "^3.1.2", optional = true}
sphinx-astropy = {version = "^1.3", optional = true}
sphinx-argparse = {version = "^0.2.5", optional = true}
nbsphinx = {version = "^0.7.1", optional = true}
sphinx-math-dollar = {version = "^1.1.1", optional = true}
pandoc = {version = "^1.0.2", optional = true}
ipykernel = {version = "^5.3.4", optional = true}
recommonmark = {version = "^0.6.0", optional = true}

[tool.poetry.extras]
test = ["pytest-astropy", "pytest", "tox"]
docs = ["sphinx", "sphinx-astropy", "sphinx-argparse", "nbsphinx", "sphinx-math-dollar", "pandoc", "ipykernel", "recommonmark"]

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^19.10b0"
importlib_resources = {version = "^2.0.1", python = "3.6"}
ipykernel = {version = "^5.3.0", optional = true}
pytest-astropy = "^0.8.0"
sphinx = "^3.1.2"
sphinx-astropy = "^1.3"
sphinx-argparse = "^0.2.5"
nbsphinx = "^0.7.1"
sphinx-math-dollar = "^1.1.1"
pandoc = "^1.0.2"
recommonmark = "^0.6.0"
pytest = "^5"

[build-system]
requires = ["poetry >= 0.12, <1"]
build-backend = "poetry.masonry.api"
