name: pygeoutils-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - setuptools
  - pip
  - pygeoogc
  - xarray
  - geopandas
  - rasterio
  - shapely
  - simplejson

  - dask
  - netCDF4
  - bottleneck

  - setuptools_scm
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - coverage
  - pip:
    - numbagg
