repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.8.0
  hooks:
  - id: reorder-python-imports
    language_version: python3
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "100"]
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: flake8
- repo: https://github.com/asottile/pyupgrade
  rev: v1.25.2
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
