language: python
python:
  - '3.6'
  - '3.8'
addons:
  apt:
    packages:
      - texlive-latex-base
      - latexmk
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=3.0
install:
  - pip install Django~=$DJANGO_VERSION
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: pypi
  user: weinbusch
  password:
    secure: n1FzYQL2HxE8sgDTfVtlLmGrd1apcGv3gpP/lWND58wYg6wfhQ/LSxNc63Qpn5w5sWeJfGxLU/DAqj9C9yZEGJv3B52QVBW6g9i+b/kjUb1DgR7id8+Oqqsp/dlFzn0MtDX+Cp1gJpf+YDUFPVDobrrepIhChvqbkx4h000aMtLq6K2ckZuYlqc/UQE2KUl1A8OfODnEkUvkf5/mzS0DQu8Yn9/Hmro6Fj9vAjEkP1n3ya5qNMse81XAuXbl32ZhtcMoNz/mL8rNNF+NPEzq0rO17DYvB2g9AZoXVR0lTVtB/C8/33SaQjtMBEa2WB0fUCpISmqqLKy2onfleyHzbIWDvgDtsxhVIRIH7FMTzJY5RMpN5dhdiWXftMNKl4GjIzxUH61DrImcdKS6L+w1cIkHUjxaHB6suHx/S5gO3hVl4GeOjB2nqzNyI/AvqLAyhjnS1XeoCNiz+QftFRrRZXwDfdpr+xP5rPVeWFpSLPRGUB41k+1vQW9hPPCxq3fq6ZADIwAo7f7wskM1QFkBWFbWKO54Q1B6hGlnBXmUFNPmhrT3Dk6OTbR+HQ/B/QHWE3bgY6HT6XbwBlhq0l9uFms3DOXRHLK7y53aiTV6JiT74VfNcAEqo5Ydx2dAj5p1dmDi7dSueydUvDh3XxjiHqc1m66ZEmMSQMZxVQaWJic=
  on:
    tags: true
    branch: master
    python: 3.8
    condition: "$DJANGO_VERSION = 3.0"
