[tool.poetry]
name = "SciFin"
version = "0.0.6"
description = "SciFin is a python package for Science and Finance."
authors = ["Fabien Nugier <fabien.nugier@outlook.com>"]

# New attributes
license = "MIT"
readme = "README.md"
homepage = "https://github.com/SciFin-Team/SciFin"
repository = "https://github.com/SciFin-Team/SciFin"
documentation = "https://github.com/SciFin-Team/SciFin/wiki"
keywords = ["SciFin", "scifin", "science", "finance"]
include = ["LICENSE"]

[tool.poetry.dependencies]
# Updated Python version
python = "^3.6"
# New dependencies
numpy = "^1.18"
pandas = "^1.0"
bs4 = "^4.7"
requests = "^2.23"
pandas_datareader = "^0.8"
IPython = "^7.13"
scipy = "^1.4"
statsmodels = "^0.11"
sklearn = "^0.22"
matplotlib = "^3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

# New scripts
[tool.poetry.scripts]
scifin = 'scifin:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


