
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-04T20:01:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1acdeeb8862bbdfe4e304eecccbad815ae6f44b3",
 "version": "v0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
