[tool.poetry]
name = "alpha-shifter-cypher"
version = "0.1.1"
description = "An example Python CLI program distributed via PyPI."
authors = ["Benjamin Rosen <ben@classy.name>"]

[tool.poetry.dependencies]
python = "^3.6"
fire = "^0.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
app = 'alpha_shifter_cypher:activate'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
