
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-28T11:37:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0644ba1397ffedb5889f04433fdce01cbf04ee5f",
 "version": "0.12.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
