[tool.black]
line-length = 88
target-version = ["py37"]

[tool.isort]
line_length = 88
indent = '    '
multi_line_output = 3
force_grid_wrap = 0
combine_as_imports = true
order_by_type = false
use_parentheses = true
include_trailing_comma = true
force_sort_within_sections = true

[tool.poetry]
name = "shinymdc"
version = "3.1.0"
description = "Tool to compile markdown files to tex/pdf using pandoc, latexmk"
readme = "README.md"
authors = ["Jayanth Koushik <jnkoushik@gmail.com>"]
license = "MIT"
repository = "https://github.com/jayanthkoushik/mdc"

packages = [{ include = "mdc" }]

classifiers=[
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
]

[tool.poetry.scripts]
mdc = "mdc.mdc:main"

[tool.poetry.dependencies]
python = "^3.6.1"
shinyutils = { extras = ["color"], version = "^4.1.6" }

[tool.poetry.dev-dependencies]
pylint = "^2.3"
isort = "^4.3"
bumpversion = "*"
pre-commit = "^1.16"
black = { version = "*", allow-prereleases = true }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
