[tool.poetry]
name = "favicons"
version = "0.0.2"
description = "Favicon generator for Python"
authors = ["checktheroads <matt@allroads.io>"]
readme = "README.md"
homepage = "https://github.com/checktheroads/favicons"
repository = "https://github.com/checktheroads/favicons"
license = "BSD-3-Clause-Clear"

[tool.poetry.dependencies]
python = "^3.6.1"
click = "^7.1"
rich = "^3.3.2"
pillow = "^7.2"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
flake8-black = "^0.2.0"
flake8-comprehensions = "^3.2.3"
flake8-bugbear = "^20.1.4"
flake8-deprecated = "^1.3"
flake8-docstrings = "^1.5.0"
flake8-if-expr = "^1.0.4"
flake8-isort = "^3.0.1"
flake8-plugin-utils = "^1.3.0"
flake8-polyfill = "^1.0.2"
flake8-print = "^3.1.4"
flake8-return = "^1.1.2"
flake8-bandit = "^2.1.2"
flake8-breakpoint = "^1.1.0"
flake8-builtins = "^1.5.3"
flake8-eradicate = "^0.4.0"
flake8-pie = "^0.5.0"
isort = "^4.3"
mccabe = "^0.6.1"
pep8-naming = "^0.11.1"
pre-commit = "^2.6.0"
mypy = "^0.782"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
