# -*- coding: utf-8 -*-
# Authored by: Josh (joshzda@gmail.com)
from setuptools import setup

setup(
    name='amazon_ad',
    version='0.0.1b4',
    packages=['amazon_ad',
              'amazon_ad.api',
              'amazon_ad.api.sb',
              'amazon_ad.api.sp',
              'amazon_ad.client',
              'amazon_ad.core',
              'amazon_ad.core.utils',
              ],
    url='',
    license='',
    author='joshzda',
    author_email='joshzda@gmail.com',
    description='Amazon Advertising SDK',
    setup_requires=['wheel'],
    install_requires=[
        "appnope==0.1.0",
        "arrow==0.12.1",
        "backcall==0.1.0",
        "certifi==2018.10.15",
        "chardet==3.0.4",
        "decorator==4.4.2",
        "idna==2.7",
        "ipython==7.2.0",
        "ipython-genutils==0.2.0",
        "jedi==0.17.0",
        "parso==0.7.0",
        "pexpect==4.8.0",
        "pickleshare==0.7.5",
        "prompt-toolkit==2.0.1",
        "ptyprocess==0.6.0",
        "Pygments==2.6.1",
        "python-dateutil==2.7.5",
        "requests==2.20.1",
        "six==1.11.0",
        "traitlets==4.3.3",
        "urllib3==1.24.1",
        "wcwidth==0.1.9",
    ],
    python_requires='>=3.6',
)
