
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-01T15:03:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef43e4692c8eefeb26180a5555594ae5eb425a9e",
 "version": "2020.08.01.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
