# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2020 Collabora, Ltd. and the Proclamation contributors

.shared:
  image: python:3.$PYTHON_MINOR
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tox
    - pip3 install pytest-cov jinja2 Click
    - tox -e py3$PYTHON_MINOR
    - pytest --cov=proclamation

python-3.5:
  variables:
    PYTHON_MINOR: 5
  extends: .shared

python-3.6:
  variables:
    PYTHON_MINOR: 6
  extends: .shared

python-3.7:
  variables:
    PYTHON_MINOR: 7
  extends: .shared

python-3.8:
  variables:
    PYTHON_MINOR: 8
  extends: .shared

linting:
  image: python:3.7
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tox
    - pip3 install flake8
    - flake8 proclamation/*.py
    - tox -e codespell

reuse:
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint

sphinx:
  image: python:3.7
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends make
    - pip3 install jinja2 && pip3 install -r docs/requirements.txt
    - make -C docs

# Publish schema
pages:
  stage: deploy
  only:
    - main
  script:
    - mkdir -p public
    - cp proclamation.schema.* public/
  artifacts:
    paths:
      - public
