
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-28T10:10:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "afd2e58d5c27db9cd1c807073de6c506ba0b5440",
 "version": "0.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
