
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-01T14:15:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e42a37441a642e1d7580fbe332c5cdad2769503c",
 "version": "2020.08.01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
