
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-31T05:47:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdb9dd517927710a6fc6f95d90923ef38d558788",
 "version": "0.4.1.post.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
