[tool.poetry]
name = "lospec2aseprite"
version = "0.1.1"
description = "Import palettes from Lospec to Aseprite"
authors = ["Konosprod <konosprod@free.fr>"]
license = "MIT"
include = ["LICENSE"]
readme = "README.md"
homepage = "https://github.com/Konosprod/lospec2aseprite"
classifiers = [
    "Topic :: Utilities",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: End Users/Desktop",
    "Environment :: Console"
]

[tool.poetry.dependencies]
python = "^3.7"
beautifulsoup4 = "^4.9.1"
requests_download = "^0.1.2"
progressbar2 = "^3.51.4"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
lospec2aseprite = "lospec2aseprite.importer:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

