apiVersion: spp.spp/v1
kind: Spp
metadata:
  name: pcap1
spec:
  ctl:
    name: ctl
    image: sppc/spp-ctl:18.04
  primary:
    name: primary
    image: sppc/spp-ubuntu:18.04
    eal:
      lcores: "1"
      socket-mem: "1024"
    portmask: "0x07"
  pcaps:
    - name: pcap:1
      image: sppc/spp-ubuntu:18.04
      eal:
        lcores: "1,13"
        socket-mem: "1024"
      port: "ring:1"
      status: "running"
    - name: pcap:2
      image: sppc/spp-ubuntu:18.04
      eal:
        lcores: "1,12"
        socket-mem: "1024"
      port: "ring:1"
      out_dir: "/var/log:/var/tmp"
      fsize: 300
      status: "idle"
