apiVersion: spp.spp/v1
kind: Spp
metadata:
  name: pipetest1
spec:
  ctl:
    name: ctl
    image: sppc/spp-ctl:18.04
  primary:
    name: primary
    image: sppc/spp-ubuntu:18.04
    eal:
      lcores: "1"
      socket-mem: "1024"
    portmask: "0x07"
  nfvs:
    - name: nfv:1
      image: sppc/spp-ubuntu:18.04
      eal:
        lcores: "2,3"
        socket-mem: "1024"
      resources: ["ring:1", "ring:2", "ring:3", "ring:4"]
      patches:
        - src: "ring:2"
          dst: "ring:3"
        - src: "ring:4"
          dst: "ring:1"
  apps:
    - name: pipe-test:1
      image: sppc/spp-ubuntu:18.04
      command: ["pipe_test"]
      args: ["net_pipe0"]
      type: "pipe"
      eal:
        lcores: "5"
        vdevs: [["net_pipe0", "rx=ring:1", "tx=ring:2"]]
    - name: pipe-test:2
      image: sppc/spp-ubuntu:18.04
      command: ["pipe_test"]
      args: ["--send net_pipe1"]
      type: "pipe"
      eal:
        lcores: "6"
        vdevs: [["net_pipe1", "rx=ring:3", "tx=ring:4"]]
