apiVersion: spp.spp/v1
kind: Spp
metadata:
  name: primary-vdev
spec:
  ctl:
    name: ctl
    image: sppc/spp-ctl:18.04
  primary:
    name: primary
    image: sppc/spp-ubuntu:18.04
    eal:
      lcores: "1"
      socket-mem: "1024"
      vdevs: [["net_tap1", "iface=foo1"]]
    portmask: "0x01"
