[tool.poetry]
name = "yaga"
version = "0.2.2"
description = "Yet Another Generic Automator"
authors = ["Joseph Egan <joseph.s.egan@gmail.com>"]
license = "MIT"

homepage = "https://github.com/eganjs/yaga"
repository = "https://github.com/eganjs/yaga"

readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
isort = "^5.1.4"
black = "^19.10b0"
flake8 = "^3.8.3"
pyprojroot = "^0.2.0"
toml = "^0.10.1"

[tool.poetry.scripts]
yaga = "yaga:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
