#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['netimages']

package_data = \
{'': ['*']}

install_requires = \
['scapy', 'Pillow', 'ansicolors']

setup(name='netimages',
      version='0.1.0',
      description='NetImages - tool for sniffing images over HTTP traffic and showing them on the console.',
      author='Anthony Shaw',
      author_email='anthonyshaw@apache.org',
      url='https://github.com/tonybaloney/netimages',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.5',
     )
