# Generated by Django 3.0.7 on 2020-06-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200619_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
