# Generated by Django 3.0.7 on 2020-06-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200626_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mtg_json_uuid',
            field=models.CharField(max_length=200),
        ),
    ]
