# Generated by Django 3.2 on 2020-07-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200717_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preferences',
            name='email_notif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_preferences',
            name='subscribe_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_preferences',
            name='view_email',
            field=models.BooleanField(default=True),
        ),
    ]
