# -*- coding: utf-8 -*-
"""adityadfunctionrec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CW1JPEooEW0rDodbyA0eE4Aw9xN61MjG
"""

def print_elist(a_list)
  for eachelement in a_list:
    if isinstance(eachelement, list):
      print_elist(eachelement)
    else:
      print(eachelement)