
# =====================================================================
# Check the RiotKit docs: https://github.com/riotkit-org/riotkit-harbor
# Good luck! All the best, RiotKit, your anarchist tech collective ;-)
# =====================================================================

# User and group that will operate the environment
deploy_user: vagrant
deploy_group: vagrant

# Directory, where the project will be installed
remote_dir: /project

# Target repository to clone (in most cases it should be the same repository as current one)
# leave commented for automatic detection
#git_url: git@github.com:your-org/your-repo.git
#git_secret_url: git@github.com:your-org/your-repo.git

# Will make a file in /etc/sudoers.d/ to allow ssh-agent passing into sudo session
configure_sudoers: yes

nodes:
    production:
        # example configuration for testing environment based on Vagrant
        # to run the environment type: harbor :deployment:vagrant -c "up --provision"
        - host: 127.0.0.1
          port: "2222"
          user: vagrant
          password: vagrant

          # relative path from ".rkd/deployment" path
          private_key: .vagrant/machines/default/virtualbox/private_key
