[tool.poetry]
name = "pypart"
version = "0.1.0"
description = ""
authors = ["Benjamin Murauer <b.murauer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sklearn = "^0.0"
pipelinehelper = "^0.7.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
pre-commit = "^2.6.0"
twine = "^3.2.0"
isort = "^5.2.1"
autoflake = "^1.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
