# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pdhttp
from pdhttp.models.error500 import Error500  # noqa: E501
from pdhttp.rest import ApiException


class TestError500(unittest.TestCase):
    """Error500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testError500(self):
        """Test Error500"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pdhttp.models.error500.Error500()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
