{% set data = load_setup_py_data(from_recipe_dir=True, recipe_dir="..") %}

package:
  name: data_pipeline_api
  version: {{ TAG }}

source:
  path: ../dist

build:
  noarch: python
  script: pip install --no-deps *.whl

requirements:
  build:
    - python
    - pip
    - setuptools_scm
    - pyyaml

  run:
    - python
  {% for package in data.get("install_requires") %}
    - {{ package }}
  {% endfor %}


test:
  imports:
    - data_pipeline_api

about:
  home: https://github.com/ScottishCovidResponse/data_pipeline_api
