exclude: '^docs/conf.py'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3 # Release 3.8.3
  hooks:
  - id: flake8
    args: ['--max-line-length=88']  # default of Black

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.2.1
  hooks:
  - id: isort
