[tool.poetry]
name = "pyutgenerator"
version = "0.2.0"
description = "python ut generator"
authors = ["shigeshige <5540474+shigeshige@users.noreply.github.com>"]
homepage = "https://github.com/shigeshige/py-ut-generator"
repository = "https://github.com/shigeshige/py-ut-generator.git"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    'Programming Language :: Python :: 3',
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Utilities",
]

[tool.poetry.scripts]
pyutgen = 'pyutgenerator.run:main'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.0"
autopep8 = "^1.5.2"
pep8 = "^1.7.1"
flake8 = "^3.7.9"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
