language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

cache: apt

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install python-numpy gfortran"

env: FC=gfortran

install:
    - "python setup.py build"
    - "python setup.py install"

script:
    - "python ./genericf2py/main.py"