
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-30T17:04:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0b281dea535a3d30ff50d17a7d2a97189ceee48",
 "version": "5.0b23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
