
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-07-27T17:12:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd335766edc479af931176183d586c0495eb7e34",
 "version": "0.20.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
