
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-22T13:19:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "19ff65d02b645f5710fbdecfd259a9d3a0f35d29",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
