- name: Allow Docker to use an insecure registry
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service

- name: Restart docker daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
