# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-03 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_item_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='amount_taxed',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, default='PCS', max_length=16, verbose_name='\u5355\u4f4d'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unit',
            field=models.CharField(blank=True, default='\u4ef6', max_length=16, verbose_name='\u5355\u4f4d'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_quotes', to=settings.AUTH_USER_MODEL, verbose_name='\u4eba\u5458'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='\u4eba\u5458'),
        ),
    ]
