
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-28T12:38:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3dd682e3be3f3906a3b0f3f65cd44e5aa09fea33",
 "version": "1.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
