# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-03 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def gen_item_customer(apps, schema_editor):
    Item = apps.get_model('quote', 'Item')
    for i in Item.objects.all():
        i.customer = i.request.customer
        i.save()


class Migration(migrations.Migration):
    dependencies = [
        ('quote', '0005_auto_20180602_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='items', to='quote.Company', verbose_name='\u5ba2\u6237'),
        ),
        migrations.RunPython(gen_item_customer)
    ]
