# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='\u540d\u5b57')),
                ('gender', models.CharField(choices=[(b'M', '\u7537'), (b'F', '\u5973')], default=b'-', max_length=1, verbose_name='\u6027\u522b')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='\u624b\u673a')),
                ('email', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='\u90ae\u7bb1')),
                ('id_card', models.CharField(blank=True, db_index=True, max_length=18, null=True, verbose_name='\u8eab\u4efd\u8bc1')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('city', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='\u57ce\u5e02')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5730\u5740')),
                ('ethnic', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u6c11\u65cf')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='saas.Party', verbose_name='\u56e2\u4f53')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_person', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '\u4e2a\u4eba',
                'verbose_name_plural': '\u4e2a\u4eba',
            },
        ),
    ]
