# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api_common.proto',
  package='cul',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61pi_common.proto\x12\x03\x63ul\"F\n\x0cUnitProgress\x12$\n\x0bworker_type\x18\x01 \x01(\x0e\x32\x0f.cul.WorkerType\x12\x10\n\x08progress\x18\x02 \x01(\x02\"+\n\tBytesData\x12\x10\n\x08pack_num\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\")\n\nDataResult\x12\x0b\n\x03num\x18\x01 \x01(\x04\x12\x0e\n\x06result\x18\x02 \x01(\t\"I\n\x11ProcessingRequest\x12\x1c\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0e.cul.BytesData\x12\x16\n\x0e\x66ile_extension\x18\x02 \x01(\t\"\xa5\x01\n\x12ProcessingResponse\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12#\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x15.cul.TicketStatusCode\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12)\n\x0eunits_progress\x18\x04 \x03(\x0b\x32\x11.cul.UnitProgress\x12\x1f\n\x06result\x18\x05 \x03(\x0b\x32\x0f.cul.DataResult\":\n\x15PackProcessingRequest\x12!\n\tpack_data\x18\x01 \x03(\x0b\x32\x0e.cul.BytesData\"~\n\x16PackProcessingResponse\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12#\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x15.cul.TicketStatusCode\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x1f\n\x06result\x18\x04 \x03(\x0b\x32\x0f.cul.DataResult*v\n\nWorkerType\x12\x06\n\x02\x62\x62\x10\x00\x12\x06\n\x02\x62t\x10\x01\x12\x06\n\x02\x66\x61\x10\x02\x12\x06\n\x02\x66\x63\x10\x03\x12\x06\n\x02\x66\x64\x10\x04\x12\x06\n\x02\x66\x65\x10\x05\x12\x06\n\x02hr\x10\x06\x12\x06\n\x02mm\x10\x07\x12\x06\n\x02pd\x10\x08\x12\x06\n\x02si\x10\t\x12\x06\n\x02sf\x10\n\x12\x07\n\x03\x62rt\x10\x0b\x12\x07\n\x03oed\x10\x0c*\\\n\x10TicketStatusCode\x12\x0b\n\x07Unknown\x10\x00\x12\x0e\n\nInProgress\x10\x01\x12\x06\n\x02OK\x10\x02\x12\x0b\n\x07Stopped\x10\x03\x12\n\n\x06\x46\x61iled\x10\x04\x12\n\n\x06Queued\x10\x05\x62\x06proto3')
)

_WORKERTYPE = _descriptor.EnumDescriptor(
  name='WorkerType',
  full_name='cul.WorkerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='bb', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bt', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fa', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fc', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fd', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='fe', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='hr', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='mm', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pd', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='si', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sf', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='brt', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='oed', index=12, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=616,
  serialized_end=734,
)
_sym_db.RegisterEnumDescriptor(_WORKERTYPE)

WorkerType = enum_type_wrapper.EnumTypeWrapper(_WORKERTYPE)
_TICKETSTATUSCODE = _descriptor.EnumDescriptor(
  name='TicketStatusCode',
  full_name='cul.TicketStatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InProgress', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Stopped', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Queued', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=736,
  serialized_end=828,
)
_sym_db.RegisterEnumDescriptor(_TICKETSTATUSCODE)

TicketStatusCode = enum_type_wrapper.EnumTypeWrapper(_TICKETSTATUSCODE)
bb = 0
bt = 1
fa = 2
fc = 3
fd = 4
fe = 5
hr = 6
mm = 7
pd = 8
si = 9
sf = 10
brt = 11
oed = 12
Unknown = 0
InProgress = 1
OK = 2
Stopped = 3
Failed = 4
Queued = 5



_UNITPROGRESS = _descriptor.Descriptor(
  name='UnitProgress',
  full_name='cul.UnitProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_type', full_name='cul.UnitProgress.worker_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress', full_name='cul.UnitProgress.progress', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=95,
)


_BYTESDATA = _descriptor.Descriptor(
  name='BytesData',
  full_name='cul.BytesData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pack_num', full_name='cul.BytesData.pack_num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='cul.BytesData.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=140,
)


_DATARESULT = _descriptor.Descriptor(
  name='DataResult',
  full_name='cul.DataResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='cul.DataResult.num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='cul.DataResult.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=183,
)


_PROCESSINGREQUEST = _descriptor.Descriptor(
  name='ProcessingRequest',
  full_name='cul.ProcessingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='cul.ProcessingRequest.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_extension', full_name='cul.ProcessingRequest.file_extension', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=258,
)


_PROCESSINGRESPONSE = _descriptor.Descriptor(
  name='ProcessingResponse',
  full_name='cul.ProcessingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='cul.ProcessingResponse.ticket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='cul.ProcessingResponse.code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='cul.ProcessingResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='units_progress', full_name='cul.ProcessingResponse.units_progress', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='cul.ProcessingResponse.result', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=426,
)


_PACKPROCESSINGREQUEST = _descriptor.Descriptor(
  name='PackProcessingRequest',
  full_name='cul.PackProcessingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pack_data', full_name='cul.PackProcessingRequest.pack_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=486,
)


_PACKPROCESSINGRESPONSE = _descriptor.Descriptor(
  name='PackProcessingResponse',
  full_name='cul.PackProcessingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='cul.PackProcessingResponse.ticket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='cul.PackProcessingResponse.code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='cul.PackProcessingResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='cul.PackProcessingResponse.result', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=614,
)

_UNITPROGRESS.fields_by_name['worker_type'].enum_type = _WORKERTYPE
_PROCESSINGREQUEST.fields_by_name['data'].message_type = _BYTESDATA
_PROCESSINGRESPONSE.fields_by_name['code'].enum_type = _TICKETSTATUSCODE
_PROCESSINGRESPONSE.fields_by_name['units_progress'].message_type = _UNITPROGRESS
_PROCESSINGRESPONSE.fields_by_name['result'].message_type = _DATARESULT
_PACKPROCESSINGREQUEST.fields_by_name['pack_data'].message_type = _BYTESDATA
_PACKPROCESSINGRESPONSE.fields_by_name['code'].enum_type = _TICKETSTATUSCODE
_PACKPROCESSINGRESPONSE.fields_by_name['result'].message_type = _DATARESULT
DESCRIPTOR.message_types_by_name['UnitProgress'] = _UNITPROGRESS
DESCRIPTOR.message_types_by_name['BytesData'] = _BYTESDATA
DESCRIPTOR.message_types_by_name['DataResult'] = _DATARESULT
DESCRIPTOR.message_types_by_name['ProcessingRequest'] = _PROCESSINGREQUEST
DESCRIPTOR.message_types_by_name['ProcessingResponse'] = _PROCESSINGRESPONSE
DESCRIPTOR.message_types_by_name['PackProcessingRequest'] = _PACKPROCESSINGREQUEST
DESCRIPTOR.message_types_by_name['PackProcessingResponse'] = _PACKPROCESSINGRESPONSE
DESCRIPTOR.enum_types_by_name['WorkerType'] = _WORKERTYPE
DESCRIPTOR.enum_types_by_name['TicketStatusCode'] = _TICKETSTATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnitProgress = _reflection.GeneratedProtocolMessageType('UnitProgress', (_message.Message,), {
  'DESCRIPTOR' : _UNITPROGRESS,
  '__module__' : 'api_common_pb2'
  # @@protoc_insertion_point(class_scope:cul.UnitProgress)
  })
_sym_db.RegisterMessage(UnitProgress)

BytesData = _reflection.GeneratedProtocolMessageType('BytesData', (_message.Message,), {
  'DESCRIPTOR' : _BYTESDATA,
  '__module__' : 'api_common_pb2'
  # @@protoc_insertion_point(class_scope:cul.BytesData)
  })
_sym_db.RegisterMessage(BytesData)

DataResult = _reflection.GeneratedProtocolMessageType('DataResult', (_message.Message,), {
  'DESCRIPTOR' : _DATARESULT,
  '__module__' : 'api_common_pb2'
  # @@protoc_insertion_point(class_scope:cul.DataResult)
  })
_sym_db.RegisterMessage(DataResult)

ProcessingRequest = _reflection.GeneratedProtocolMessageType('ProcessingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSINGREQUEST,
  '__module__' : 'api_common_pb2'
  # @@protoc_insertion_point(class_scope:cul.ProcessingRequest)
  })
_sym_db.RegisterMessage(ProcessingRequest)

ProcessingResponse = _reflection.GeneratedProtocolMessageType('ProcessingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSINGRESPONSE,
  '__module__' : 'api_common_pb2'
  # @@protoc_insertion_point(class_scope:cul.ProcessingResponse)
  })
_sym_db.RegisterMessage(ProcessingResponse)

PackProcessingRequest = _reflection.GeneratedProtocolMessageType('PackProcessingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PACKPROCESSINGREQUEST,
  '__module__' : 'api_common_pb2'
  # @@protoc_insertion_point(class_scope:cul.PackProcessingRequest)
  })
_sym_db.RegisterMessage(PackProcessingRequest)

PackProcessingResponse = _reflection.GeneratedProtocolMessageType('PackProcessingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PACKPROCESSINGRESPONSE,
  '__module__' : 'api_common_pb2'
  # @@protoc_insertion_point(class_scope:cul.PackProcessingResponse)
  })
_sym_db.RegisterMessage(PackProcessingResponse)


# @@protoc_insertion_point(module_scope)
