# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BodyTrackerService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndlapi.api._pyproto import api_common_pb2 as api__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BodyTrackerService.proto',
  package='cul',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x42odyTrackerService.proto\x12\x03\x63ul\x1a\x10\x61pi_common.proto2\xb0\x01\n\x0b\x42odyTracker\x12K\n\x14process_video_stream\x12\x16.cul.ProcessingRequest\x1a\x17.cul.ProcessingResponse(\x01\x30\x01\x12T\n\x15process_images_stream\x12\x1a.cul.PackProcessingRequest\x1a\x1b.cul.PackProcessingResponse(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[api__common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BODYTRACKER = _descriptor.ServiceDescriptor(
  name='BodyTracker',
  full_name='cul.BodyTracker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=52,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='process_video_stream',
    full_name='cul.BodyTracker.process_video_stream',
    index=0,
    containing_service=None,
    input_type=api__common__pb2._PROCESSINGREQUEST,
    output_type=api__common__pb2._PROCESSINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='process_images_stream',
    full_name='cul.BodyTracker.process_images_stream',
    index=1,
    containing_service=None,
    input_type=api__common__pb2._PACKPROCESSINGREQUEST,
    output_type=api__common__pb2._PACKPROCESSINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BODYTRACKER)

DESCRIPTOR.services_by_name['BodyTracker'] = _BODYTRACKER

# @@protoc_insertion_point(module_scope)
