- job:
    name: networking-spp-tempest-test
    parent: base
    vars:
      devstack_localrc:
        USE_PYTHON3: True

- project:
    networking-spp-integration-ci:
      jobs:
        - networking-spp-tempest-test
    templates:
       - check-requirements
       - openstack-python3-ussuri-jobs
