# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20171114_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clazz',
            name='primary_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clazzs', to='school.Teacher', verbose_name='\u73ed\u4e3b\u4efb'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='session',
            name='begin_date',
            field=models.DateField(blank=True, verbose_name='\u5f00\u59cb\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='\u7ed3\u675f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='\u540d\u79f0'),
        ),
    ]
