# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_szuprefix.utils.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20180201_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clazz',
            name='student_names',
            field=django_szuprefix.utils.modelutils.WordSetField(blank=True, default=[], help_text='\u5b66\u751f\u59d3\u540d\uff0c\u4e00\u884c\u4e00\u4e2a', verbose_name='\u5b66\u751f\u540d\u518c'),
        ),
        migrations.AlterField(
            model_name='clazz',
            name='teacher_names',
            field=django_szuprefix.utils.modelutils.KeyValueJsonField(blank=True, default={}, help_text="\u8001\u5e08\u804c\u8d23\u4e0e\u8001\u5e08\u59d3\u540d\u7528':'\u9694\u5f00\uff0c\u4e00\u884c\u4e00\u4e2a, \u5982:<br/>\n                                                 \u73ed\u4e3b\u4efb:\u4e01\u4e00\u6210<br/>\n                                                 \u8bed\u6587:\u4e01\u4e00\u6210<br/>\n                                                 \u6570\u5b66:\u6797\u5a1f", verbose_name='\u8001\u5e08\u540d\u518c'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduate_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graduate_students', to='school.Session', verbose_name='\u6bd5\u4e1a\u5c4a\u522b'),
        ),
    ]
