# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20180323_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clazz',
            name='entrance_session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrance_clazzs', to='school.Session', verbose_name='\u5165\u5b66\u5c4a\u522b'),
        ),
    ]
