# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20180713_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='\u4ee3\u7801'),
        ),
        migrations.AddField(
            model_name='major',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='\u4ee3\u7801'),
        ),
    ]
