# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-13 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20180713_2355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='college',
            unique_together=set([('school', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='major',
            unique_together=set([('school', 'code')]),
        ),
    ]
