# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-12 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_party_type'),
        ('school', '0018_auto_20190308_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('party', 'number')]),
        ),
    ]
