# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-07-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200513_1359'),
        ('school', '0029_auto_20200401_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='clazz',
        ),
        migrations.AddField(
            model_name='clazz',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', related_query_name='class', to='school.Major', verbose_name='\u4e13\u4e1a'),
        ),
        migrations.AddField(
            model_name='major',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='school_majors', to='course.Course', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
