# Generated by Django 3.0.8 on 2020-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200730_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_updated',
            field=models.CharField(default='2020-08-01T21:08:23.761043', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_updated',
            field=models.CharField(default='2020-08-01T21:08:23.762270', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='notification',
            name='price_threshold',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
