[tool.poetry]
name = "python-syncthing"
version = "3.0.0"
description = "Python bindings to the Syncthing REST interface."
authors = ["Blake VandeMerwe <blakev@null.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.24.0"
pendulum = "^2.1.2"
yarl = "^1.4.2"

[tool.poetry.dev-dependencies]
yapf = "^0.30.0"
isort = "^5.1.4"
codespell = "^1.17.1"
invoke = "^1.4.1"
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
