# Generated by Django 3.2 on 2020-07-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200716_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaar_user',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
