[tool.poetry]
name = "queueless"
version = "0.1.0"
description = "Database-based task management for python"
authors = ["Exhor"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
dill = "*"
sqlalchemy = "*"
psycopg2 = "^2.8.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
