name: ldcpy
channels:
  - conda-forge
dependencies:
  - cartopy=0.18
  - netcdf4
  - pip
  - xarray
  - zfpy
  - xrft
  - cmocean
  - numpy
  - scipy
  - matplotlib
  - dask
  - intake-esm
  - cython
  - scikit-image
  - opencv
