# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180713_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='exam_papers',
            field=models.ManyToManyField(blank=True, related_name='course_chapters', to='exam.Paper', verbose_name='\u8bd5\u5377'),
        ),
    ]
