# Generated by Django 3.0.7 on 2020-07-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Article Title')),
                ('url', models.TextField(verbose_name='Article URL')),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(verbose_name='Article Summary')),
                ('company', models.TextField(verbose_name='Article Company')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Username')),
                ('apple', models.BooleanField(default=True)),
                ('google', models.BooleanField(default=True)),
                ('facebook', models.BooleanField(default=True)),
                ('microsoft', models.BooleanField(default=True)),
                ('amazon', models.BooleanField(default=True)),
                ('samsung', models.BooleanField(default=True)),
                ('IBM', models.BooleanField(default=True)),
                ('twitter', models.BooleanField(default=True)),
                ('netflix', models.BooleanField(default=True)),
                ('oracle', models.BooleanField(default=True)),
                ('SAP', models.BooleanField(default=True)),
                ('salesforce', models.BooleanField(default=True)),
                ('tesla', models.BooleanField(default=True)),
            ],
        ),
    ]
