[tool.poetry]
name = "dsets"
version = "0.0.1"
description = ""
authors = ["Alexander Hungenberg <alexander.hungenberg@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
