version: "3"

services:
  dev:
    build: ./
    volumes:
      - ./:/map2loop-2
    ports:
      - 8888:8888
    deploy:
      resources:
        # limits:
        #   cpus: "0.001"
        #   memory: 50M
        reservations:
          # cpus: "0.0001"
          memory: 4G
