[build-system]
requires = ["setuptools>=30.3.0",
            "setuptools_scm",
            "wheel",
            "oldest-supported-numpy",
            "extension-helpers"]
build-backend = "setuptools.build_meta"
