[tool.poetry]
name = "run-all-the-tests"
version = "0.1.13"
authors = ["Greg Kedge <gregwork@kedges.com>"]
description = "Make sure both 'python -m pytest' and 'pytest' run your tests."
readme = "README.md"
homepage = "https://github.com/gkedge/run-all-the-tests"
repository = "https://github.com/gkedge/run-all-the-tests"
license = "MIT"
keywords = ["testing", "pytest", "sys.path", "packaging", "dependency", "pyproject.toml"]
include = ["docs/**/*"]

classifiers = [
        "Programming Language :: Python :: 3",
        "Topic :: Software Development :: Testing",
        "Topic :: Software Development :: Libraries",
	    "Topic :: Utilities",
        "Operating System :: OS Independent",
        "Natural Language :: English",
        "Intended Audience :: Developers",
]

[tool.pylint.basic]
good-names = "ii,jj,kk,ex,_"

[tool.pylint.messages_control]
disable = "bad-continuation, missing-module-docstring, missing-function-docstring, missing-class-docstring"

[tool.pylint.format]
max-line-length = "100"

[tool.black]
line-length = 100
target-version = ['py37']
include = '\.pyi?$'

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/gkedge/run-all-the-tests/issues"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = {extras = ["d"], version = "^19.10b0"}
pylint = "^2.5.3"
pytest = "^5.4.3"
wheel = "tox-wheel"
pytest-dependency = "^0.5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
