#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sortpy', 'sortpy.tests']

package_data = \
{'': ['*']}

setup(name='sortpy',
      version='1.0.8',
      description='This module contains some popular sorting algorithms implemented in pure python.',
      author='Denis Anikin',
      author_email='ad@xfenix.ru',
      url='https://github.com/xfenix/xfsort',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.7',
     )
