# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOV1QU9mJJUtUpQnz2a3B1hJ6qhCNxAu
"""

from distutils.core import setup

setup(
    name = 'durvankurbfunctionrec',
    version = '1.0.0',
    py_modules = ['durvankurbfunctionrec'],
    author = 'durvya_0509',
    description = 'A recusrion function to print every item in the list'
)
