# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-05-13 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target_user_tags',
            field=models.CharField(blank=True, help_text='\u7b26\u5408\u6807\u7b7e\u7684\u4eba\u624d\u80fd\u586b\u5199\u95ee\u5377,\u7559\u7a7a\u5219\u6240\u6709\u4eba\u5747\u53ef\u586b\u5199\u4f46\u4e0d\u4f1a\u53d1\u4e2a\u4eba\u901a\u77e5.<p>\u4f8b\u5b50:<p>\u8001\u5e08:\u5f20\u4e09,\u674e\u56db,\u8d75\u4e94<p>\u5b66\u751f:*<p>\u5b66\u751f.\u5e74\u7ea7:\u5927\u4e00,\u5927\u4e8c<p>\u5b66\u751f.\u5165\u5b66\u5c4a\u522b:2019\u5c4a<p>\u5b66\u751f.\u73ed\u7ea7:2018\u7ea7\u6570\u5b57\u5a92\u4f53201801\u73ed,2018\u7ea7\u6570\u5b57\u5a92\u4f53201804\u73ed', max_length=255, null=True, verbose_name='\u76ee\u6807\u4eba\u7fa4\u6807\u7b7e'),
        ),
    ]
