# Generated by Django 3.0.7 on 2020-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200619_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='color_id',
        ),
        migrations.AddField(
            model_name='card',
            name='card_color',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.DeleteModel(
            name='Card_Color',
        ),
    ]
