# Generated by Django 3.2 on 2020-07-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200715_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaar_user',
            name='location_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
