# Generated by Django 3.2 on 2020-07-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_seller_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaar_user',
            name='completed_sales',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='completed_sales',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='location_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
