# Generated by Django 3.2 on 2020-07-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200716_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RenameField(
            model_name='bazaar_user',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seller_type',
        ),
    ]
