# Generated by Django 3.2 on 2020-07-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200717_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='equal_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='greater_than_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='less_than_flag',
            field=models.BooleanField(default=True),
        ),
    ]
