# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-04 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0007_auto_20191101_1652'),
        ('media', '0006_auto_20200225_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7')),
                ('url', models.URLField(verbose_name='\u7f51\u5740')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u6709\u6548')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('owner_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_images', to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_images', to='saas.Party', verbose_name='\u56e2\u4f53')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_images', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '\u56fe\u7247',
                'verbose_name_plural': '\u56fe\u7247',
            },
        ),
        migrations.AddField(
            model_name='lecturer',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='\u5934\u50cf'),
        ),
    ]
