[tool.poetry]
name = "stocksmith"
version = "0.1.0"
description = ""
authors = ["Saakshaat <saakshaat2001@gmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
