
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-31T11:46:53+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f73b0a158de6273aa6c9ad65dafe7638de4e1f0",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
