[tool.poetry]
name = "thm"
version = "0.1.0"
description = "Automatic script downloads & note uploads for TryHackMe's Kali"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
