# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cogneed-protos/audio-stream/audio-stream-api/audio-stream-api-service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cogneed_protos.audio_stream.common import common_pb2 as cogneed__protos_dot_audio__stream_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cogneed-protos/audio-stream/audio-stream-api/audio-stream-api-service.proto',
  package='ai.cogneed.cloud.speech.v1',
  syntax='proto3',
  serialized_options=_b('\n\032ai.cogneed.cloud.speech.v1P\001'),
  serialized_pb=_b('\nKcogneed-protos/audio-stream/audio-stream-api/audio-stream-api-service.proto\x12\x1a\x61i.cogneed.cloud.speech.v1\x1a/cogneed-protos/audio-stream/common/common.proto\"\x97\x01\n\x12\x41udioDetectRequest\x12>\n\x04init\x18\x01 \x01(\x0b\x32..ai.cogneed.cloud.speech.v1.InitSessionRequestH\x00\x12\x36\n\x05\x61udio\x18\x02 \x01(\x0b\x32%.ai.cogneed.cloud.speech.v1.AudioBlobH\x00\x42\t\n\x07request2\x87\x01\n\x12StreamAudioService\x12q\n\x0cstream_audio\x12..ai.cogneed.cloud.speech.v1.AudioDetectRequest\x1a-.ai.cogneed.cloud.speech.v1.DetectionResponse(\x01\x30\x01\x42\x1e\n\x1a\x61i.cogneed.cloud.speech.v1P\x01\x62\x06proto3')
  ,
  dependencies=[cogneed__protos_dot_audio__stream_dot_common_dot_common__pb2.DESCRIPTOR,])




_AUDIODETECTREQUEST = _descriptor.Descriptor(
  name='AudioDetectRequest',
  full_name='ai.cogneed.cloud.speech.v1.AudioDetectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='init', full_name='ai.cogneed.cloud.speech.v1.AudioDetectRequest.init', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio', full_name='ai.cogneed.cloud.speech.v1.AudioDetectRequest.audio', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='ai.cogneed.cloud.speech.v1.AudioDetectRequest.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=157,
  serialized_end=308,
)

_AUDIODETECTREQUEST.fields_by_name['init'].message_type = cogneed__protos_dot_audio__stream_dot_common_dot_common__pb2._INITSESSIONREQUEST
_AUDIODETECTREQUEST.fields_by_name['audio'].message_type = cogneed__protos_dot_audio__stream_dot_common_dot_common__pb2._AUDIOBLOB
_AUDIODETECTREQUEST.oneofs_by_name['request'].fields.append(
  _AUDIODETECTREQUEST.fields_by_name['init'])
_AUDIODETECTREQUEST.fields_by_name['init'].containing_oneof = _AUDIODETECTREQUEST.oneofs_by_name['request']
_AUDIODETECTREQUEST.oneofs_by_name['request'].fields.append(
  _AUDIODETECTREQUEST.fields_by_name['audio'])
_AUDIODETECTREQUEST.fields_by_name['audio'].containing_oneof = _AUDIODETECTREQUEST.oneofs_by_name['request']
DESCRIPTOR.message_types_by_name['AudioDetectRequest'] = _AUDIODETECTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioDetectRequest = _reflection.GeneratedProtocolMessageType('AudioDetectRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUDIODETECTREQUEST,
  __module__ = 'cogneed_protos.audio_stream.audio_stream_api.audio_stream_api_service_pb2'
  # @@protoc_insertion_point(class_scope:ai.cogneed.cloud.speech.v1.AudioDetectRequest)
  ))
_sym_db.RegisterMessage(AudioDetectRequest)


DESCRIPTOR._options = None

_STREAMAUDIOSERVICE = _descriptor.ServiceDescriptor(
  name='StreamAudioService',
  full_name='ai.cogneed.cloud.speech.v1.StreamAudioService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=311,
  serialized_end=446,
  methods=[
  _descriptor.MethodDescriptor(
    name='stream_audio',
    full_name='ai.cogneed.cloud.speech.v1.StreamAudioService.stream_audio',
    index=0,
    containing_service=None,
    input_type=_AUDIODETECTREQUEST,
    output_type=cogneed__protos_dot_audio__stream_dot_common_dot_common__pb2._DETECTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMAUDIOSERVICE)

DESCRIPTOR.services_by_name['StreamAudioService'] = _STREAMAUDIOSERVICE

# @@protoc_insertion_point(module_scope)
