# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-05 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20190322_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('view_all_person', '\u67e5\u770b\u6240\u6709\u4e2a\u4eba'),), 'verbose_name': '\u4e2a\u4eba', 'verbose_name_plural': '\u4e2a\u4eba'},
        ),
    ]
