[tool.poetry]
name = "algopedia"
version = "0.1.0"
description = ""
authors = ["Marcelo Trylesinski <marcelotryle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
coverage = {extras = ["toml"], version = "^5.2.1"}
flake8 = "^3.8.3"
flake8-bugbear = "^20.1.4"
black = "^19.10b0"
mypy = "^0.782"
pytest-cov = "^2.10.0"

[tool.poetry.extras]
test = ["pytest --cov=algopedia --cov-fail-under=100"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
