
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-27T10:31:47+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d7bc6c973f287c160758138edc85f73624f33a2",
 "version": "1.25.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
