# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inference.proto',
  package='inference',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0finference.proto\x12\tinference\"Y\n\x16ObjectDetectionRequest\x12\x14\n\x0crequest_info\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\x03\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\"=\n\x03\x42ox\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04ymin\x18\x02 \x01(\x02\x12\x0c\n\x04xmax\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\"C\n\x06Object\x12\x1b\n\x03\x62ox\x18\x01 \x01(\x0b\x32\x0e.inference.Box\x12\r\n\x05score\x18\x02 \x01(\x02\x12\r\n\x05label\x18\x03 \x01(\x03\"f\n\x17ObjectDetectionResponse\x12\x15\n\rresponse_info\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\x03\x12\"\n\x07objects\x18\x03 \x03(\x0b\x32\x11.inference.Object*P\n\rKeyObjectType\x12\x0e\n\nBACKGROUND\x10\x00\x12\t\n\x05MONEY\x10\x01\x12\x0b\n\x07\x43\x41SHBOX\x10\x02\x12\n\n\x06MOBILE\x10\x03\x12\x0b\n\x07SCANNER\x10\x04\x32n\n\x12KeyObjectDetection\x12X\n\x0f\x44\x65tectKeyObject\x12!.inference.ObjectDetectionRequest\x1a\".inference.ObjectDetectionResponseb\x06proto3'
)

_KEYOBJECTTYPE = _descriptor.EnumDescriptor(
  name='KeyObjectType',
  full_name='inference.KeyObjectType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BACKGROUND', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONEY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CASHBOX', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCANNER', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=357,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_KEYOBJECTTYPE)

KeyObjectType = enum_type_wrapper.EnumTypeWrapper(_KEYOBJECTTYPE)
BACKGROUND = 0
MONEY = 1
CASHBOX = 2
MOBILE = 3
SCANNER = 4



_OBJECTDETECTIONREQUEST = _descriptor.Descriptor(
  name='ObjectDetectionRequest',
  full_name='inference.ObjectDetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_info', full_name='inference.ObjectDetectionRequest.request_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_version', full_name='inference.ObjectDetectionRequest.model_version', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='inference.ObjectDetectionRequest.image_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=119,
)


_BOX = _descriptor.Descriptor(
  name='Box',
  full_name='inference.Box',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xmin', full_name='inference.Box.xmin', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ymin', full_name='inference.Box.ymin', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xmax', full_name='inference.Box.xmax', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ymax', full_name='inference.Box.ymax', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=182,
)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='inference.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='box', full_name='inference.Object.box', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='inference.Object.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='inference.Object.label', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=251,
)


_OBJECTDETECTIONRESPONSE = _descriptor.Descriptor(
  name='ObjectDetectionResponse',
  full_name='inference.ObjectDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_info', full_name='inference.ObjectDetectionResponse.response_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='inference.ObjectDetectionResponse.category', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects', full_name='inference.ObjectDetectionResponse.objects', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=355,
)

_OBJECT.fields_by_name['box'].message_type = _BOX
_OBJECTDETECTIONRESPONSE.fields_by_name['objects'].message_type = _OBJECT
DESCRIPTOR.message_types_by_name['ObjectDetectionRequest'] = _OBJECTDETECTIONREQUEST
DESCRIPTOR.message_types_by_name['Box'] = _BOX
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['ObjectDetectionResponse'] = _OBJECTDETECTIONRESPONSE
DESCRIPTOR.enum_types_by_name['KeyObjectType'] = _KEYOBJECTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectDetectionRequest = _reflection.GeneratedProtocolMessageType('ObjectDetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTDETECTIONREQUEST,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ObjectDetectionRequest)
  })
_sym_db.RegisterMessage(ObjectDetectionRequest)

Box = _reflection.GeneratedProtocolMessageType('Box', (_message.Message,), {
  'DESCRIPTOR' : _BOX,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.Box)
  })
_sym_db.RegisterMessage(Box)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.Object)
  })
_sym_db.RegisterMessage(Object)

ObjectDetectionResponse = _reflection.GeneratedProtocolMessageType('ObjectDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTDETECTIONRESPONSE,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ObjectDetectionResponse)
  })
_sym_db.RegisterMessage(ObjectDetectionResponse)



_KEYOBJECTDETECTION = _descriptor.ServiceDescriptor(
  name='KeyObjectDetection',
  full_name='inference.KeyObjectDetection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=439,
  serialized_end=549,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectKeyObject',
    full_name='inference.KeyObjectDetection.DetectKeyObject',
    index=0,
    containing_service=None,
    input_type=_OBJECTDETECTIONREQUEST,
    output_type=_OBJECTDETECTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KEYOBJECTDETECTION)

DESCRIPTOR.services_by_name['KeyObjectDetection'] = _KEYOBJECTDETECTION

# @@protoc_insertion_point(module_scope)
