[tool.poetry]
name = "swagger_diff"
version = "0.1.1"
description = ""
authors = ["jun <wandy1208@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.5.1"
jinja2 = "^2.11.2"
dictdiffer = "^0.8.1"
click = "^7.1.2"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
swagger-diff = 'swagger_diff.main:main'

[[tool.poetry.source]]
name = "aliyun"
url = "http://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

