# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-30 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0024_auto_20200628_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='target_users',
            field=models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='\u53c2\u4e0e\u4eba'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='actual_user_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='\u5b9e\u9645\u53c2\u4e0e\u4eba\u6570'),
        ),
    ]
