# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-16 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0008_auto_20200515_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='saas_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
