# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-14 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='\u540d\u5b57')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u672a\u5b89\u88c5'), (1, '\u5df2\u5b89\u88c5')], default=1, verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='saas.Party', verbose_name='\u56e2\u4f53')),
            ],
            options={
                'verbose_name': '\u5e94\u7528',
                'verbose_name_plural': '\u5e94\u7528',
            },
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set([('party', 'name')]),
        ),
    ]
