[tool.poetry]
name = "deshima-sensitivity"
version = "0.2.3"
description = "Sensitivity calculator for DESHIMA-type spectrometers"
authors = ["Akira Endo <a.endo@tudelft.nl>"]
maintainers = [
    "Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>",
    "Yohei Togami <y.togami@a.phys.nagoya-u.ac.jp>",
    "Keiichi Matsuda <matsuda@a.phys.nagoya-u.ac.jp>",
    "Masato Hagimoto <hagimoto@a.phys.nagoya-u.ac.jp>",
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/deshima-dev/deshima-sensitivity"

[tool.poetry.dependencies]
python = "^3.6"
matplotlib = "^3.1"
numpy = "^1.17"
scipy = "^1.4"
pandas = ">= 0.25, < 1.1"
jupyter-io = "^0.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
black = "^19.10b0"
pytest = "^5.3"
jupyterlab = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
