# Generated by Django 3.2 on 2020-06-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_collection_collection_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='color_id',
        ),
        migrations.AddField(
            model_name='card',
            name='color_id',
            field=models.ManyToManyField(to='main.Card_Color'),
        ),
    ]
