# Generated by Django 2.0.13 on 2020-06-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200625_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_keywords',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='cmc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='prices',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image_loc',
            field=models.ImageField(upload_to=''),
        ),
    ]
