# -*- coding:utf-8 -*- 
# author = 'denishuang'
from __future__ import unicode_literals

REQUEST_STATUS_CANCEL = 0
REQUEST_STATUS_REQUEST = 1
REQUEST_STATUS_QUOTE = 2
REQUEST_STATUS_SEND = 4
REQUEST_STATUS_SUCCESS = 8
REQUEST_STATUS_FAIL = 16

CHOICES_REQUEST_STATUS = (
    (REQUEST_STATUS_CANCEL, '取消'),
    (REQUEST_STATUS_REQUEST, '询价中'),
    (REQUEST_STATUS_QUOTE, '报价中'),
    (REQUEST_STATUS_SEND, '已发送询价'),
    (REQUEST_STATUS_SUCCESS, '中标'),
    (REQUEST_STATUS_FAIL, '失标')
)


PATHS_REQUEST_STATUS = {
    REQUEST_STATUS_REQUEST: [REQUEST_STATUS_QUOTE, REQUEST_STATUS_SEND, REQUEST_STATUS_CANCEL],
    REQUEST_STATUS_QUOTE: [REQUEST_STATUS_SEND],
    REQUEST_STATUS_SEND: [REQUEST_STATUS_SUCCESS, REQUEST_STATUS_FAIL],
}
