# Generated by Django 3.0.7 on 2020-07-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizzbuzz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='IBM',
            new_name='ibm',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='SAP',
            new_name='sap',
        ),
        migrations.AddField(
            model_name='preferences',
            name='spacex',
            field=models.BooleanField(default=True),
        ),
    ]
