# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-17 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0007_auto_20191101_1652'),
        ('dailylog', '0002_auto_20200210_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_date', models.DateField(db_index=True, verbose_name='\u65e5\u671f')),
                ('owner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7')),
                ('metics', models.CharField(max_length=128, verbose_name='\u6307\u6807')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='\u6570\u503c')),
                ('owner_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dailylog_records', to='saas.Party', verbose_name='\u56e2\u4f53')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dailylog_records', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '\u8bb0\u5f55',
                'verbose_name_plural': '\u8bb0\u5f55',
            },
        ),
        migrations.AlterField(
            model_name='stat',
            name='owner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b'),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('the_date', 'owner_type', 'owner_id', 'metics', 'user')]),
        ),
    ]
