# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_paper_is_break_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='questions_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='\u9898\u6570'),
        ),
    ]
