# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-14 03:04
from __future__ import unicode_literals

from django.db import migrations, models


def save_old_answer_std_score(apps, schema_editor):
    Answer = apps.get_model('exam', 'Answer')
    ids= list(Answer.objects.values_list('id',flat=True))
    for id in ids:
        print id
        try:
            a = Answer.objects.get(id=id)
            a.std_score=a.performance.get('stdScore', 0)
            a.save()
        except Exception,e:
            print e



class Migration(migrations.Migration):
    dependencies = [
        ('exam', '0008_paper_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='std_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='\u5206\u6570'),
        ),
        migrations.RunPython(save_old_answer_std_score)
    ]
