# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-04-27 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_szuprefix.utils.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0007_auto_20191101_1652'),
        ('dailylog', '0004_auto_20200415_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7')),
                ('owner_name', models.CharField(blank=True, default='', max_length=256, verbose_name='\u5c5e\u4e3b\u540d\u79f0')),
                ('owner_group', models.CharField(blank=True, default='', max_length=256, verbose_name='\u5c5e\u4e3b\u5206\u7ec4')),
                ('user_name', models.CharField(blank=True, default='', max_length=256, verbose_name='\u7528\u6237\u59d3\u540d')),
                ('user_group', models.CharField(blank=True, default='', max_length=256, verbose_name='\u7528\u6237\u5206\u7ec4')),
                ('detail', django_szuprefix.utils.modelutils.JSONField(blank=True, default={}, verbose_name='\u8be6\u60c5')),
                ('target', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u76ee\u6807')),
                ('accomplish', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u5b8c\u6210')),
                ('accumulate', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u7d2f\u8ba1\u5b8c\u6210')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='\u5b8c\u6210\u767e\u5206\u6bd4')),
                ('times', models.PositiveSmallIntegerField(default=0, verbose_name='\u6b21\u6570')),
                ('score', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='\u5f97\u5206')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('owner_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dailylog_performances', to='saas.Party', verbose_name='\u56e2\u4f53')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dailylog_performances', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '\u8868\u73b0',
                'verbose_name_plural': '\u8868\u73b0',
            },
        ),
    ]
