# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-17 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailylog', '0006_auto_20200501_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='record',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7'),
        ),
    ]
