[tool.poetry]
name = "ry"
version = "0.0.0"
description = ""
authors = ["ryan <ryan?@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
