
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-28T17:29:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f40b7f5498078db896b93a5c4a4d85a27a06cdb",
 "version": "0.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
