from whisper_evaluate.statistics import Statistics
from whisper_evaluate.whisper_statistics import WhisperStatistics
from whisper_evaluate.netease_statistics import NetEaseStatistics
from whisper_evaluate.report import Report
import sys
