# Generated by Django 3.0.4 on 2020-03-07 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_passwordcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_column='kind', max_length=64)),
                ('value', models.CharField(db_column='value', max_length=64)),
                ('realm', models.ForeignKey(db_column='realm_name', on_delete=django.db.models.deletion.PROTECT, to='iam.Realm')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='principals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'principals',
                'default_permissions': [],
                'unique_together': {('realm', 'kind', 'value'), ('subject', 'kind', 'value')},
            },
        ),
    ]
