
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-28T12:43:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b3933c54bd18cc6bff686a53bcc6cbeb838889b",
 "version": "0.3.6.post.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
