
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-30T17:00:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "691e0b4c7be638b74332a99d87240f5a88145be9",
 "version": "1.13.0.post.dev9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
