
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-04T03:21:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d052e49c324346cec2f001b1ca22977d2859f8e2",
 "version": "1.13.0.post.dev19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
