  
[tool.poetry]
name = "cosmoplotian"
version = "0.0.1"
description = "cosmoplotian is for plotting"
authors = ["Ben Thorne <bn.thorne@googlemail.com>"]
readme = "README.rst"
repository = "https://github.com/bthorne93/cosmoplotian"

[tool.poetry.dependencies]
python = "^3.6"
astropy = "^4.0.1"
sphinx = {version = "^3.0.4", optional = true}
sphinx-astropy = {version = "^1.3", optional = true}
nbsphinx = {version = "^0.7.0", optional = true}
sphinx-math-dollar = {version = "^1.1.1", optional = true}
pandoc = {version = "^1.0.2", optional = true}
ipykernel = {version = "^5.3.0", optional = true}
numpy = "^1.17 || ^1.18"
matplotlib = "^3.0.0"
pytest = {version = "^5.4.3", optional = true}
pytest-astropy = {version = "^0.8.0", optional = true}
tox = {version = "^3.15.1", optional = true}
importlib_resources = {version = "^2.0.1", python = "3.6"}
reproject = "^0.7.1"
sphinx-argparse = "^0.2.5"

[tool.poetry.extras]
test = ["pytest", "pytest-astropy", "tox"]
docs = ["sphinx", "sphinx-astropy", "sphinx-argparse", "nbsphinx", "sphinx-math-dollar", "pandoc", "ipykernel"]


[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^19.10b0"
[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "oldest-supported-numpy",
            "cython==0.29.14"]

build-backend = 'setuptools.build_meta'
