# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_stat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ('-is_active', 'title', '-create_time'), 'verbose_name': '\u8bd5\u5377', 'verbose_name_plural': '\u8bd5\u5377'},
        ),
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=models.TextField(blank=True, help_text="\u7f16\u8f91\u6307\u5357:\n\u9996\u884c\u4e3a\u6807\u9898.\n\u9898\u578b\u7528\u4e2d\u6587\u6570\u5b57\u52a0\u70b9\u53f7\u5f00\u5934.\n\u9898\u76ee\u7528\u963f\u62c9\u4f2f\u6570\u5b57\u52a0\u70b9\u53f7\u5f00\u5934.\n\u7b54\u6848\u9009\u9879\u7528\u82f1\u6587\u5b57\u6bcd\u52a0\u70b9\u53f7\u5f00\u5934.\n\u6b63\u786e\u7b54\u6848\u7528'\u7b54\u6848:'\u5f00\u5934", null=True, verbose_name='\u5185\u5bb9'),
        ),
    ]
