# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-11 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20200301_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='owner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='owner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b'),
        ),
    ]
