# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-08 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_auto_20200513_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='correct_straight_times',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='\u8fde\u7eed\u7b54\u5bf9\u6b21\u6570'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='corrected',
            field=models.BooleanField(default=False, verbose_name='\u5df2\u8ba2\u6b63'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='times',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='\u6b21\u6570'),
        ),
    ]
