[tool.poetry]
name = "repldb-client-py"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
setuptools = "^47.3.1"
twine = "^3.2.0"
wheel = "^0.34.2"
http3 = "^0.6.7"
requests-async = "^0.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
