dist: trusty
sudo: required
services:
  - docker
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=pep8
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 2.7
      env: TOXENV=py27-codecov
    - python: 2.7
      env: TOXENV=py27-etcd
    - python: pypy
      env: TOXENV=pypy-etcd
    - python: 3.5
      env: TOXENV=py35-etcd
    - python: 3.6
      env: TOXENV=py36-etcd
  allow_failures:
    - python: pypy
      env: TOXENV=pypy-etcd
    - python: 3.5
      env: TOXENV=py35-etcd
    - python: 3.6
      env: TOXENV=py36-etcd

before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - python -m pip install pip -U
  - python -m pip install tox coverage coveralls
  - python -m virtualenv --version
  - python -m easy_install --version
  - python -m pip --version
  - python -m tox --version
script:
  - tox
