[tool.poetry]
name = "graphene_pydantic"
version = "0.1.0"
description = "Graphene Pydantic integration"
readme = "README.md"
repository = "https://github.com/upsidetravel/graphene-pydantic"
authors = [
  "Rami Chowdhury <rami@upside.com>"
]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: Implementation :: PyPy",
]
keywords = ["api", "graphql", "protocol", "rest", "relay", "graphene", "pydantic", "model"]

[tool.poetry.dependencies]
python = "^3.6"
# To keep things simple, we only support newer versions of Graphene & Pydantic
graphene = ">=2.1.3,<3"
pydantic = ">=1.0,<=1.6"

[tool.poetry.dev-dependencies]
pytest = "~4.6.4"
pytest-cov = "~2.7.1"
tox = "~3.12.0"  # sync with tox.ini
mypy = "0.720"
black = "19.3b0"
pre-commit = "~1.17.0"
tox-gh-actions = "^1.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
