# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-02 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20180527_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='\u5355\u53f7'),
        ),
    ]
