# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-07 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20180604_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delivery',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8d27\u671f'),
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_days_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u8d27\u671f\u6700\u77ed\u5929\u6570'),
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_days_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u8d27\u671f\u6700\u957f\u5929\u6570'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u672a\u7a0e\u5355\u4ef7'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price_taxed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u542b\u7a0e\u5355\u4ef7'),
        ),
    ]
