
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-28T21:47:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ff4b8825e8136641ac1bd852fbcfecc0b1ded6b",
 "version": "0.2.0.post.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
