[tool.poetry]
name = "cotoba-cli"
version = "1.3.0b1"
description = ""
authors = []
exclude = ["integration_tests", "run_integration_test.sh"]

[tool.poetry.scripts]
cotoba = "cotoba_cli.cli:main"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
boto3 = "^1.14.20"
pytz = "^2020.1"
python-jose = "^3.1.0"
requests = "^2.24.0"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
freezegun = "^0.3.15"
pep8-naming = "^0.11.1"
pytest = "^5.4.3"
mock = "^4.0.2"
pytest-mock = "^3.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
