# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20190514_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='exam_papers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='exam_papers',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.Category', verbose_name='\u7c7b\u522b'),
        ),
    ]
