# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-22 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('-', '\u672a\u77e5'), ('M', '\u7537'), ('F', '\u5973')], default='-', max_length=1, verbose_name='\u6027\u522b'),
        ),
    ]
