# -*- coding:utf-8 -*-
from __future__ import unicode_literals
PARTY_STATUS_TEST = 0
PARTY_STATUS_USING = 1
PARTY_STATUS_GIVEUP = 2
PARTY_STATUS_STOP = 4
CHOICES_PARTY_STATUS = (
    (PARTY_STATUS_TEST, '测试中'),
    (PARTY_STATUS_USING, '正式使用'),
    (PARTY_STATUS_GIVEUP, '放弃'),
    (PARTY_STATUS_STOP, '停止使用')
)

PARTY_TYPE_COMPANY = 1
PARTY_TYPE_SCHOOL = 2

CHOICES_PARTY_TYPE = (
    (PARTY_TYPE_COMPANY, '公司'),
    (PARTY_TYPE_SCHOOL, '学校')
)

# WORKER_STATUS_WORKING = 1
# WORKER_STATUS_QUIT = 2
# WORKER_STATUS_VACATION = 4
#
# CHOICE_WORKER_STATUS = (
#     (WORKER_STATUS_WORKING, u'在职'),
#     (WORKER_STATUS_QUIT, u'离职'),
#     (WORKER_STATUS_VACATION, u'休假')
# )

APP_STATUS_UNINSTALL = 0
APP_STATUS_INSTALL = 1

CHOICES_APP_STATUS = (
    (APP_STATUS_UNINSTALL, "未安装"),
    (APP_STATUS_INSTALL, "已安装"),
)

CHOICES_APPS = (
    ('school', '学校'),
    ('course', '课程'),
    ('exam', '测验'),
)