# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-05-15 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_auto_20191101_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='logo',
            field=models.URLField(blank=True, help_text='Logo\u56fe\u7247Url', null=True, verbose_name='\u6807\u8bc6'),
        ),
        migrations.AlterField(
            model_name='party',
            name='slug',
            field=models.CharField(blank=True, help_text='\u4f5c\u4e3a\u5b50\u57df\u540d\u4f7f\u7528', max_length=16, unique=True, verbose_name='\u7f16\u53f7'),
        ),
    ]
