# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-17 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django_szuprefix.utils.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0009_role_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=django_szuprefix.utils.modelutils.JSONField(blank=True, default={}, verbose_name='\u6743\u9650'),
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='saas_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
