[tool.poetry]
name = "feature-graph"
version = "0.3.2"
description = "A simple DAG orchestrator built specifically for machine learning feature generation"
license="MIT"
readme="README.md"
repository="https://github.com/mvanwyk/feature_graph"
authors = ["Murray Vanwyk"]

[tool.poetry.dependencies]
python = "^3.7"
graphviz = "^0.14.1"
loguru = "^0.5.1"
google-cloud-bigquery = "^1.25.0"
SqliteDict = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyterlab = "^2.2.0"
flake8 = "^3.8.3"
pytest-cov = "^2.10.0"
pre-commit = "^2.6.0"
black = "^19.10b0"
coveralls = "^2.1.1"
docstr-coverage = "^1.2.0"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/mvanwyk/feature_graph/issues"

[build-system]
requires = ["poetry^1.0.9"]
build-backend = "poetry.masonry.api"

