
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-30T16:34:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b647bcaa3b28b1edf98cc72a15b25d976e3e87e5",
 "version": "0.11.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
