# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-27 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20180527_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='item',
        ),
    ]
