# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-27 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_remove_quote_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount_taxed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u542b\u7a0e\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='quote',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u672a\u7a0e\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='quote',
            name='amount_taxed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u542b\u7a0e\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='quote',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='quote',
            name='unit',
            field=models.CharField(default='\u4ef6', max_length=16, verbose_name='\u5355\u4f4d'),
        ),
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u672a\u7a0e\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='request',
            name='amount_taxed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u542b\u7a0e\u91d1\u989d'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u672a\u7a0e\u91d1\u989d'),
        ),
    ]
