# Generated by Django 3.0.4 on 2020-03-18 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0013_auto_20200318_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectBooleanProperty',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('kind', models.CharField(db_column='kind', max_length=127)),
                ('value', models.BooleanField(db_column='value')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='booleanproperties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subjectbooleanproperties',
                'default_permissions': [],
                'default_related_name': 'booleanproperties',
                'unique_together': {('subject', 'kind')},
            },
        ),
    ]
