
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-27T17:31:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "aebe790d6a05fbe95bcabe5037a6019ada85afac",
 "version": "0.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
