# Config file for automatic testing at travis-ci.org
os: linux
language: python
cache: pip

env:
  global:
    PYTEST_ADDOPTS="--cov-append"

script:
  - tox -e $TOX_ENV

install:
  - pip install tox codecov
  - tox --notest -e $TOX_ENV

after_success:
- codecov

jobs:
  include:
    - stage: test
      python: 3.7
      env:
        TOX_ENV: py37-tests

    - stage: test
      python: 3.8
      env:
        TOX_ENV: py38-tests

    - stage: test
      python: 3.6
      env:
        TOX_ENV: py36-tests

    - python: 3.8
      env:
        TOX_ENV: check-lint,docs

    - stage: deploy
      if: tag IS present
      python: 3.8
      before_install: true
      script: true
      install: true
      after_success: true
      deploy:
        provider: pypi
        on:
          repo: peopledoc/sphinx-github-changelog
          tags: true
        username: __token__
        password:
          secure: "UrFMQh8BTWiypZCRbVIAOUqoCvRynh7a1ebR/k1wE+nNp9U0RelTabdoVd6jF0BypUHGfpwRJV+3+kXkUm7xi0W24kz1S8HkkSbcU50q6zhostMmMaBYwiCYyop0LIPWZPkrfl2xJWDPJKBgZpAr9Oce+oFnvgseW3f8Z1jKlqvLl9k5zMAgdTBjKm7F5ToRoY0udV6NcRNfXoaf50DcIazycN68+17qmuOwnAIx3zBwoxn7WefHFwTmQEad1jIrQhy4+ZmvQLqnJPeRBGeqxMKXRcx/YhybV30f2eEMgQGRgXWg2aDbOeUURrFbrhKAbuULaC4pmx9ExpnyRmf8i+B1q7VLfFRfOWBH6uSlgVEJ5zpGtQUf6M666B8RxuKSDPhB+ozu4PvNRHgTQhTofOITm3SrHzaouv+vvRLMSh8AScQAJ2q1W8n+KTzciRlV/q+RRPUPoIEtjnr+FegiGng3eIfseeYXdX1tJbIlXv60ydagJtFvQGPhqQLwPNAs8NiBgXT4Olch0f9/DY3LgkIS6RnXZolq/GrlsUQI22UwpVcTCmHMrP5R1AO3ElO19bx/Qrrp4bPFyIXg17PhS17BKDZZa28HZ/lbk3ckMXp+wJZoywGot7Xv3R//Zw8b8u7MG1D7Av7iX46Z5nPctmyFsykafkqR4s/V5SSY22Q="
