# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-31 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='\u56de\u8d34\u6570'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
