
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-27T14:56:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "de1a5a81fe0d4b52b5e245a759236c1ff16b2f45",
 "version": "0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
