
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-31T03:39:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "565f29e65d7e460785e1bf82710dd222133837f3",
 "version": "1.13.0.post.dev13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
