[tool.poetry]
name = "atek_main"
version = "0.1.4"
description = "Core tools for ATEK"
authors = ["JediHero <hansen.rusty@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sshtunnel = "^0.1.5"
pandas = "^1.0.5"
cytoolz = "^0.10.1"
mysql-connector-python = "^8.0.21"
pymysql = "^0.10.0"
tabulate = "^0.8.7"
python-dotenv = "^0.14.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
