
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-05T18:42:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "15e0b399e7f8a859ded516a9b7dbcd620d1bac9b",
 "version": "0.5.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
