# Generated by Django 2.0.13 on 2020-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200621_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tcg_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image_loc',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='product_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
