# Generated by Django 3.0.8 on 2020-07-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200729_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_updated',
            field=models.CharField(default='2020-07-30T07:44:50.070222', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_updated',
            field=models.CharField(default='2020-07-30T07:44:50.072559', max_length=200),
        ),
    ]
