[tool.poetry]
name = "subtitle-sync"
version = "0.2.8"
description = ""
authors = ["VVNoodle <brickkace@gmail.com>"]
exclude = ["mvp_screenplays/", "mvp_subtitles/", "matchingTest.json"]

[tool.poetry.dependencies]
python = "^3.7"
Scrapy = "^2.0.1"
subliminal = "^2.0.5"
srt = "^3.0.0"
spacy = "^2.2.4"
pysbd = "^0.2.3"
tensorflow_hub = "^0.8.0"
matplotlib = "^3.2.2"
numpy = "^1.19.0"
strsimpy = "^0.1.7"
tensorflow = "^2.2.0"
tensorflow-gpu = "^2.2.0"
flake8 = "^3.8.3"
black = "^19.10b0"
rope = "^0.17.0"
num2words = "^0.5.10"
unidecode = "^1.1.1"
pep8 = "^1.7.1"
autopep8 = "^1.5.3"
pylint = "^2.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
