# Config file for automatic testing at travis-ci.com

stages:
  - test
  - deploy

# defining the unittest jobs
unittest: &unittest
  stage: test
  os: linux
  dist: bionic
  language: python
  cache: pip
  install: 
    - python3 --version
    - python3 -m pip install tox-travis
  script: tox

jobs:
  include:
    # test stage
    - <<: *unittest
      python: 3.6
      env: TOXENV=py36

    - <<: *unittest
      python: 3.6
      env: TOXENV=coverage

    - <<: *unittest
      python: 3.6
      env: TOXENV=flake8

    - <<: *unittest
      python: 3.7
      env: TOXENV=py37

    - <<: *unittest
      python: 3.8
      env: TOXENV=py38

    - <<: *unittest
      os: osx
      osx_image: xcode11.2  # Python 3.7.X running on macOS 10.14
      language: shell
      env:
        - TOXENV=py37
        - NOT_ON_GOLD_HOST=yup

    - stage: deploy
      script: skip
      deploy:
        cleanup: true
        provider: pypi
        distributions: sdist bdist_wheel
        skip_existing: true
        user: __token__
        password:
          secure: cz+nxXRskQOWmticDYihkMh9hiJaDHkV7kGcKq7FfGDyEM0O4/Ktnw/AWRou8EnESGx7eYUpPjC52FEtU9EFFTgDAQjabC6Ily2G5BP8iDj+tr0hYkXS+9KLpaUMC38mhQZUDhS7O+QKyVoadt7MBJ0hMw8cVxFuxosKMTz2XcTQlgtcMojNpgEvyDq0pqDA82GX1knsyHAOYzBPhdCzcLt8pp1vU7QKbeJcI6LSeBtPgp6uhVoLaoi11AyOPsWFkEemmKJgG/dAa/sho5CKeiwuSJwzRmCwQGDVtZ3K4R9/fErvoEVc4xdEG+Mm2Yds0pWY9dpWv9khxvg9PIkZ0L+kw5YOHkwg4EVlJqejKWKRtQUSrVeapQ3Da1zcuS/6CMwpLLVEoGg2ifOkruJsGWKb6fMRDGPq976e1rkU5M6tCsoZs8ipC8VCzHzdZC5KxKYEmsYlZRUNwBgJIBih8Vmotlq9DJBS7xPUHO2nFHQQzCfrviIVU8XJLWPAHxb+ai9s4HDp/ObqYs0LK161iQRYPHE6PLdUGp7/ohx5gDnPBV1GmINHuQo4UVAzr3MZY4tCyjY+09qzgjDSm+T6nR20Bi2iQwu5Z4w6q3OwufEoc59qfZrmNUhGVjjF76aoC6z0A9/ITf8RAqttt1o6XSLU83ZWmn47tzYW129aI60=
        on:
          tags: true
          repo: scotthavens/pysnobal
        

  allow_failures:
    - python: 3.6
      env: TOXENV=flake8