data_directory: data
access_log: access-{run_id}.yaml
fail_on_hash_mismatch: True
namespace: simple_network_sim
read:
  - where:
      data_product: human/mixing-matrix
      component: mixing-matrix
  - where:
      data_product: human/commutes
  - where:
      data_product: human/compartment-transition
  - where:
      data_product: human/population
      version: 0.1.0
  - where:
      data_product: human/infection/SARS-CoV-2/symptom-probability
      namespace: SCRC
  - where:
      data_product: human/infection/SARS-CoV-2/scotland/mortality
      namespace: SCRC

write:
  - where:
      {}
    use:
      source: simple_network_sim
