[tool.poetry]
name = "django-multifactor"
version = "0.4.3"
description = "Drop-in multifactor authentication subsystem for Django."
authors = ["Oli Warner <oli@thepcspy.com>"]
repository = "https://github.com/oliwarner/django-multifactor"
homepage = "https://github.com/oliwarner/django-multifactor"
readme = 'README.md'
license = "MIT"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Framework :: Django :: 3.1",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include="multifactor", from="." },
]
include = [
    'multifactor/templates/**',
    'multifactor/static/**',
]

[tool.poetry.dependencies]
python = "^3.5"
django = ">= 2.2, < 3.2"
pyotp = '^2.3'
python-u2flib-server = '^5.0'
python-jose = '^3'
fido2 = '0.8.1'

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"
dephell = "*"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
