
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-30T09:32:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f6fc72a50e2387e6f1b19f55ec0c24d52036677",
 "version": "2.2.0dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
